### ISSUE TITLE
Message "Command whoami is not answered in time" after server reboot

### ISSUE THREAD

**Issue by Rido** [TheHolyWaffle/TeamSpeak-3-Java-API#1]
Hey,

I've tried to simulate a server breakdown to check the "auto connect" function, but it seems that this does not quite work very well. 
I stopped the server and after a few seconds I restarted the server.

Then I received the message: [DEBUG] [SEVERE] Command whoami is not answered in time.

Am I doing something wrong or doesn't the bot contain an auto connect function?

Thanks!

**Comment by 1n9i9c7om** [comment]
It appears that this issue still occurs, right? Quite annoying, because I got daily reboots. :/

**Comment by Firedroide** [comment]
@1n9i9c7om

Yes, you're right. We still haven't discussed reconnection behaviour for our queries, yet.
I'll have to get together with @TheHolyWaffle for this one.

What you could do in the meantime would be to check for a disconnection manually in a kind of "watchdog" thread. It's not efficient, it's not pretty, but it should work.

You could check `query.getSocket().isConnected()` and simply create a new query if the server were to go down. I realize this is not at all a pretty solution. Unfortunately, implementing something like this directly in the API is not as easy as just calling a reconnect method. I fear that especially the asynchronous API (for whose creation I was responsable) will complicate the implementation of a reconnection feature :/

**Comment by Kaos1337** [comment]
Hello,
I'm following your suggestion to use `query.getSocket().isConnected()` to check the connection status. It's all implemented into a thread that every X seconds checks it but even if I restart the ts3 server manually the result is still true (= is connected) and I receive the messages:
```
[SEVERE] TS3 command error: {msg=server is shutting down, id=1026}
[WARNING] SocketReader has stopped!
```
Isn't it strange?

**Comment by Scrumplex** [comment]
I just check if api.whoAmI is null

**Comment by Firedroide** [comment]
@Kaos1337 I got a notification about your comment yesterday but completely forgot to answer, sorry for that.

Yeah, my previous comment was wrong. There is actually no straightforward way to find out if the socket has been disconnected.

What actually happens - if I recall correctly - is that in case of a spontaneous disconnect, reading from the `InputStream` will throw an IOException, whereas writing to the `OutputStream` just blocks indefinitely.

Anyways - I've been working a little bit (but not much since I'm rather busy with studying, expect more progress during the holidays) on creating a process to resolve a disconnect -> reconnect situation. Unfortunately, this API has not been designed with these issues in mind so I've needed to do a bit of refactoring and some other stuff might stop working, e.g. TS3Config#setLoginCredentials will probably be removed and TS3Api#login will have to replace it.

So the issue really isn't as simple as if (disconnected()) reconnect(); on the API side, especially if we want to let your server queries continue at the point where they left off, i.e. logged in, on a virtual server and probably in a channel other than the default one, with events registered, and so on.

As @Scrumplex pointed out, some kind of watchdog might be a good solution for now - though I don't think you'll encounter disconnects very often.

**Comment by Kaos1337** [comment]
No problem for the delayed reply, yesterday evening I was able to achieve the target looking the response of `apiSync.whoAmI().getId()` however is nice the check of only `apiSync.whoAmI()` as @Scrumplex suggested, more direct.

**Comment by Firedroide** [comment]
Seeing how [release 1.0.13](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/releases/tag/v1.0.13) has finally added an official reconnect API, I think it's time to close this issue.

Be sure to check out [`ReconnectExample.java`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/v1.0.13/example/ReconnectExample.java) to get familiar with this new part of the API :smile:
