### ISSUE TITLE
Create channel

### ISSUE THREAD

**Issue by ElDzi** [TheHolyWaffle/TeamSpeak-3-Java-API#123]
Hi!
http://prntscr.com/by34bo
I wanna create channel between this channels ;> How can i move / create this channel?

**Comment by Firedroide** [comment]
Set [`ChannelProperty.CHANNEL_ORDER`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/ChannelProperty.java#L56) to the ID of the channel above where you want the channel to go - either via `editChannel` or by adding it to the map you pass along to `createChannel`.

By the way, if you have lots of short and easy-to-answer questions, consider asking them over at our [Gitter Channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) instead of creating an issue report here which spams everyone with emails.
