### ISSUE TITLE
tcp_nodelay?

### ISSUE THREAD

**Issue by Kakifrucht** [TheHolyWaffle/TeamSpeak-3-Java-API#127]
I noticed in the changelogs for server version 3.0.13 
``+ Enable "tcp_nodelay" option for server query (less latency)``
Shouldn't this improve the speeds for the queries? I'm unsure if one needs to configure anything on servers end to make this work, I didn't notice any difference and there was still a delay on all API calls the bot did.

**Comment by Firedroide** [comment]
First of all, what is `tcp_nodelay`: It turns off [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) on the TCP level. In short, Nagle's algorithm will stop small chunks of data from being sent until a TCP `ACK` is received for the last piece of data that was sent.

It would certainly help reduce latency in our case (even though only a small bit), if we actually sent lots of small packets without waiting for a response.

However, this is not at all what happens. Before sending the next command to the TS3 server, we're currently waiting for the whole response to the last command to be received *and parsed*. So we're not only waiting for the last write to be `ACK`ed, but also for a few more data packets after that and maybe even another round of `ACK`s back and forth ^^

In most use-cases, this is not even the limiting factor, though, because even after all previous reads have been handled, we always wait for at least 50 milliseconds before sending the next command - even on the "`UNLIMITED`" flood rate.

So really, this API is not optimized for command throughput and this has also never been a huge priority for us.

I already have a plan on how to change `QueryIO` to be much better at handling lots of commands at once. As a nice little side effect, this will also clean up a lot of the command sending internals and remove lots of warts like the callback map or the `sent` and `answered` boolean flags as well as the `reset` method in `Command`.

If @TheHolyWaffle happens to be around: Is there a reason why we're waiting 50 milliseconds even on `UNLIMITED`? Or could this be removed / set to 0 without side effects?

**Comment by TheHolyWaffle** [comment]
Honestly, I have no idea why there is a 50 ms lowerlimit. If any, it would
have been because even unlimited in TS3 terms is not unlimited. But I doubt
that's the case, so we should be safe removing that lower limit.

As an other suggestion about the flood rate, I've encountered several
servers that will ban you even for using the default floodrate (350 ms). In
order for the api to be able to be used on those servers, we should let the
dev give the option to choose his own delay (in ms) instead of the enum
Floodrate which cannot be changed.

2016-08-10 13:16 GMT+02:00 Roger Baumgartner <notifications@github.com>:

**Comment by Firedroide** [comment]
Holy shit that was a fast response :smile:

Alright then, I guess I'll start working on that stuff. To retain at least some compatibility with older versions of the API, I'll do the following:

1. `FloodRate` stays but will go from being an enum to a class
2. Have `DEFAULT` and `UNLIMITED` be public static final fields
3. Add a `custom(int ms)` factory method to create new `FloodRate`s to pass into `TS3Query`
4. Actually respect the timeout in `SocketReader` instead of having it be at least 50 ms

**Comment by TheHolyWaffle** [comment]
Sounds great. Make sure to test out the removal of the 50 ms delay with a
real server before committing it.

2016-08-10 13:30 GMT+02:00 Roger Baumgartner <notifications@github.com>:

**Comment by Firedroide** [comment]
My localhost server doesn't seem to complain 😛 
I'll run some more tests on it, though, just to be sure.

Performance is looking extremely good: my `clientupdate`-spam benchmark currently handles about 3750 commands per second and reports no problems 😄 

This might just be because I'm connecting via localhost, though, so I'd be very thankful if someone could provide me with a server I could run a few thousand more `clientupdate`s against 😛 

One problem with us not waiting for the server's response to arrive is that our log no longer strictly follows the command-response pattern. It's now possible that multiple commands are sent before a response to the first command arrives. I'll maybe have to add some kind of number to the command so the communications log doesn't lose that information.

I'll also consider making the maximum amount of sent-but-unanswered commands configurable. Setting the value to 1 would basically revert to the old way of waiting for the response to arrive before sending the next command.

There's also currently a 280 milliseconds startup delay between the last line of the "server greeting" and the first command that's sent out. I'll see what's up with that and whether there's something I can do about it.

**Comment by Firedroide** [comment]
So apparently 200 milliseconds of those 280 ms startup time is just the class loading for all of those tiny command classes used in `TS3Api` and `TS3ApiAsync` 😞 

In the future, we should maybe look into grouping those command classes together into a few larger classes (e.g. ClientCommands, FileTransferCommands). Since all of the command classes only have 1 - 2 constructors each and no fields or methods, these classes might as well not exist. Instead we could have multiple functions inside those larger classes that just spit out a customized `Command` instance instead.

**Comment by Firedroide** [comment]
Improved `UNLIMITED` command throughput in 4ba902d1d5437e690704ba35f614dddeb1a5dd87, also includes `TCP_NODELAY`.

**Comment by Kakifrucht** [comment]
Nice, will try that out ASAP.

**Comment by Kakifrucht** [comment]
Works perfectly, amazing!
