### ISSUE TITLE
Receiving Private Messages

### ISSUE THREAD

**Issue by xeroe** [TheHolyWaffle/TeamSpeak-3-Java-API#130]
Hello,
Is it possible to let the query receive private text messages?
It seems that the eventlistener only reacts to global and channel messages, but i would like to use the private chat to send commands to my bot.
Using telnet its possible to recieve private messages via query, so it sould technically be possible with the api too right?
Am i doing something wrong or is this feature not implemented yet?

**Comment by YvesW** [comment]
Take a look at https://theholywaffle.github.io/TeamSpeak-3-Java-API/1.0.13/com/github/theholywaffle/teamspeak3/api/event/TS3EventType.html and https://theholywaffle.github.io/TeamSpeak-3-Java-API/1.0.13/com/github/theholywaffle/teamspeak3/api/TextMessageTargetMode.html#CLIENT
Haven't tested it, but I guess this should be what you need:

```
api.registerEvent(TS3EventType.TEXT_PRIVATE);

//other code here

@Override
			public void onTextMessage(TextMessageEvent e) {
				// Only react to channel messages not sent by the query itself
				if (e.getTargetMode() == TextMessageTargetMode.CLIENT) {
//code
				}
			}
```

**Comment by xeroe** [comment]
The problem is that the TextMessageEvent doesnt even fire when i send a message from a Ts3Client to the QueryClient.
When sendig in global or channel chat the Event fires, it even does when the Query sends a private message to a client, but not from client to query.

**Comment by xeroe** [comment]
Ok i solved the problem.
While debugging my bot for some reason a few query connections did stay alive after stopping the program. I dont know why, but they somehow prevented the bot from receiving said messages.

**Comment by Firedroide** [comment]
Yeah, you need to remember to terminate your program. Server Queries behave very strangely if there's suddenly two or more with the same login on the same server 😛 

If you want to terminate your program gracefully, remember to call `TS3Query#exit`. This will shut down all threads this API keeps around (and of course, when all threads in your program have terminated, your program will shutdown gracefully).

Since the issue seems to be resolved, I'll go ahead and close this issue now.
For short questions, we also have a [Gitter channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). Questions likely get answered quicker over there since there's usually more people around ^^

Thanks to @YvesW for the correct solution :smile:
