### ISSUE TITLE
Which Event for joining an Channel

### ISSUE THREAD

**Issue by BrummBrumm03** [TheHolyWaffle/TeamSpeak-3-Java-API#137]
Hello, im from Germany. 
I want to code an bot who messages all Clients with the ServerGroup 9 if a client goes into Channel 23.
How can i do this?

**Comment by rogermb** [comment]
Hi!

It's probably best to start with [ChatBotExample](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ChatBotExample.java), since that example shows you the basics of the query interface and also shows you how to set up an event handler.

What you'll need to do differently is that

* You'll need to register for the event type `TS3EventType.CHANNEL`, since you want to get notifications about clients moving from channel to channel
* Your event handler won't have to override `onTextMessage(TextMessageEvent e)`, but rather `onClientMoved(ClientMovedEvent e)`
* You'll need to use `ClientMovedEvent #getTargetChannelId` to verify that the client who moved actually moved into the channel you're monitoring
* To notify server group 9, you can get a list of all clients (`TS3Api#getClients`), then filter out the ones who are in that server group (`Client#isInServerGroup`) and finally, notify them by sending them a text message, as shown in `ChatBotExample`.

That should probably be all you need to know to get started. Happy coding!

**Comment by BrummBrumm03** [comment]
Thanks a lot, it works.
