### ISSUE TITLE
TS NOT FOUND?

### ISSUE THREAD

**Issue by Seltrox** [TheHolyWaffle/TeamSpeak-3-Java-API#140]
Hey i have a ts by ts3 cloud and if i paste the ip and port (in query port the port) the bot says: Unknow Host
But i can join and more.
If i make it on localhost or .de domain it works :c

**Comment by rogermb** [comment]
Make absolutely sure your host and port numbers are correct. Make sure there's no firewall blocking your application.

To test whether the problem is your computer / network, you can try to establish a connection to your TS3 server with the `telnet` command (on Windows, and you might need to enable that tool first, see google for that).

In a CMD, issue the following commands

```
> telnet
> o yourHostNameOrIPhere queryPort
```

If a telnet was able to connect and you received the TS3 "welcome message", you're not correctly entering the hostname and port numbers into the `TS3Config` object. But if the connection couldn't be established, the problem lies somewhere else.

Oh, and it could also be that you're using TS3DNS. This API currently doesn't support TS3DNS, so you'll have to use the actual host name and port numbers of the server.

**Comment by rogermb** [comment]
Closed due to inactivity - over a week with no response on a trivial issue.
