### ISSUE TITLE
Is it possible to set an users avatar?

### ISSUE THREAD

**Issue by iRaphi** [TheHolyWaffle/TeamSpeak-3-Java-API#141]
See title, I was wondering If & How I could set a users avatar, if thats possible.

Thanks

**Comment by rogermb** [comment]
Hi! Sorry it took me so long to respond to your issue.

I've investigated a bit, and as it looks at the moment, it doesn't seem to be possible to change other people's avatars with the server query interface.

It might just be possible to set the avatar of the TS client associated with the used server query login, but I don't think that's what you were asking about (since you could also just do that manually).
