### ISSUE TITLE
Getting List of Clients from Channel Object

### ISSUE THREAD

**Issue by darkpolice** [TheHolyWaffle/TeamSpeak-3-Java-API#143]
Sorry if I completely missed out something in the documentation.

I have noticed that we can't get a list of client id from a channel object. However, it is entirely possible to get the [channel id from a client object](http://theholywaffle.github.io/TeamSpeak-3-Java-API/1.0.13/com/github/theholywaffle/teamspeak3/api/wrapper/Client.html#getChannelId--).

Right now the only solution I can think of is to loop through each client connected to the server and map out which channel each client is connected. I often find this slow, buggy and it would be great if there is an alternative.

Thank you!

**Comment by Scrumplex** [comment]
Because of the TeamSpeak 3 ServerQuery interface we are limited to the functionalities implemented in this Java API. As fas as I know this API has implemented all functionalitites available in the ServerQuery interface, except the file transfer. So your own solution would be the best you could code at the moment.

**Comment by darkpolice** [comment]
Thank you for your prompt reply. If that's the case, I will close this issue.

**Comment by rogermb** [comment]
Hi, just to clear a few things up a bit:

This API tries to only be a relatively thin wrapper around the query interface.

Due to this, we have restricted ourselves to only offering methods that dispatch actual server query commands from the `TS3Api` and the `TS3ApiAsync` class. This is why there is no `Channel#getClients()` method. On the other hand, the client information returned in `clientlist` or `clientinfo` already contains the channel ID, so you can query that information without having to send an actual command to the server.

Apart from that, there is also no dedicated command that would return only the clients in one specific channel - there's only `clientlist`, which as you know returns all online clients.

Furthermore, especially with the quick adoption of Java 8, a collection of `Client` objects can very easily be converted to a map from channel IDs to a list of the clients in that channel.

Example:

```java
api.getClients().stream()
                .collect(Collectors.groupingBy(Client::getChannelId));
```

Adding a `getClientsByChannel(int channelId)` method that calls `getClients()` and does this filtering would save you from having to program this on your own, but I fear that if we were to implement such a function, people would start iterating over all channels and calling this method repeatedly. Each method call would of course send its own `clientlist` command and the user would end up sending one command for each channel on the server instead of one command in total.

Most server query applications which really need good performance are bounded by the amount of commands they send (especially when dealing with the 3 commands per second rate limit), so keeping the amount of commands sent as low as possible is paramount.

---

On another note: we've actually recently added support for file transfers (see 165739aa9b0d2255f3e48a4d0137ed7e6ad8c53a), that change has just not rolled out into an "official" release yet.

This doesn't mean that all commands the server query interface offers are actually supported, though. There are a few very rarely used commands (e.g.`servertemppasswordadd`) which this API doesn't support - mainly because nobody has ever asked for them, and probably nobody would ever actually use them.

---

Hopefully this was able to clear up why such a method to get all clients in a channel doesn't exist.
If you have any other questions, feel free to re-open this issue, create a new issue or joins us on our [Gitter channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) :smile:
