### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Najlepszy56** [TheHolyWaffle/TeamSpeak-3-Java-API#145]
Hello,
I have a small problem with leaks memory. The problem is shown in the pictures.
http://iv.pl/images/57024511644580724552.png

My code:
Main(App):
http://pastebin.com/ChATC547
Ts3Connect:
http://pastebin.com/uJTHkHvQ
Events:
http://pastebin.com/C6xjsAxx
Database:
http://pastebin.com/NFiyfC6x
RegisterSystem:
http://pastebin.com/UnjBZbvD
WelcomeMessage:
http://pastebin.com/gVzGk1Kn

**Comment by Kakifrucht** [comment]
Can you paste your code in a better readable format (pastebin etc.)?

**Comment by Najlepszy56** [comment]
I Changed.

**Comment by Kakifrucht** [comment]
You should use async api on anything you do off the main thread, although that wouldn't really explain the leak.

**Comment by rogermb** [comment]
Hi! I somehow completely missed this issue, sorry about that!

First of all, I think it's much more likely that you're simply accumulating tons of our objects in your `Config` class (which you also haven't uploaded) than that there is a memory leak. But I'd love to be proven wrong! 

Grab a heap analyzer and create some heap dumps (e.g. at the start of the application and after memory use has increased significantly). To do this, you could use the `jvisualvm` application from the `bin` directory of your JDK install.

If there is actually a memory leak that is caused by us, you should see a huge increase of instances of objects **that are owned by our classes** from the first to the second heap dump.

I also noticed that you're using a database. Just to remind you: Databases will use tons of memory, often as much as the system has to offer, to speed up requests (by caching and similar techniques). Make sure the increased memory footprint isn't caused by the database or the JDBC drivers you're using to connect to your database from Java.

Aside from that: You should *really* read up on at least the basics of object oriented programming and Java in particular before doing some extensive coding with an API you don't know yet. No offense, but your code doesn't adhere to any kind of OOP programming structure and was quite frankly terrible to read.

**Comment by rogermb** [comment]
Closed due to lack of input and evidence.
