### ISSUE TITLE
sendPrivateMessage

### ISSUE THREAD

**Issue by Hakens** [TheHolyWaffle/TeamSpeak-3-Java-API#148]
Hello, i have one question, i do bot who sends private message when someone logs in to ts3, but my message its longer than 1024 UTF-8 bytes, How i can separate messages, and send them in one time?
Ty for ur answer!
My code:
separated, but its sending one by one line by line, not all once;/
```
api.sendPrivateMessage(jegoid, System.lineSeparator()+"[b]◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ");
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Witaj [color=blue]"+nickwchodzacego+"[/color] na Serwerze[i][b][color=red]Ts4u.pl[/color][/b][/i]"+System.lineSeparator()+System.lineSeparator());
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"--------------------------------[color=green]Informacje[/color]-------------------------------- ");
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Pierwsza wizyta: "+"[i][color=red]"+datapokonwersji+"[/color][/i]"+", to już Twoja "+"[i][color=red]"+ilerazypolaczony+"[/color][/i]"+" wizyta na naszym serwerze!");
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Korzystasz z TS3 w wersji "+wersjatsa3+" na platformie "+platforma);
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Twój adres IP to "+jegoip);
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Twoje ID na naszym serwerze to: "+jegodbid);
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"Obecnie jest "+"[i][color=red]"+terazonline+"[/color][/i]"+"/"+"[i][color=red]512[/color][/i]"+" użytkowników");
					api.sendPrivateMessage(jegoid, System.lineSeparator());
					api.sendPrivateMessage(jegoid,"◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥     Życzymy miłej rozmowy![i][b][color=blue]~Ekipa Ts4u.pl[/color][/b][/i] ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥ ◣◥");
```

**Comment by rogermb** [comment]
Hi!

As you certainly know, this API is only a Java wrapper around the [Server Query interface](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf) TS3 provides (and a thin wrapper at that). Thus we can only provide you with the commands the query interface offers.

Unfortunately, the `sendtextmessage` command limits the size of the message to send to 1024 UTF-8 bytes.  This is a limit we can't extend and there also isn't an option to send multiple messages at once. Thus the only way to send longer messages is to send multiple separate messages, as you're already doing.

That isn't an optimal solution because of the delay between commands, though. To reduce this delay, make sure to use the `FloodRate.UNLIMITED` flood rate setting (don't forget to whitelist the IP of your query!). In a recent commit which hasn't made it into a release build yet, we've removed all restrictions on this `UNLIMITED` setting so all commands are actually sent at the highest possible throughput. You can get the most recent build from our [Frankenstein-esque GitHub Maven repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.14-SNAPSHOT).

As an alternative solution I could offer this:

The information you want to provide to clients seems like mostly basic information. You could also try moving some of this information to the server's welcome message, the virtual server description or to a channel's description and periodically update that information by using a Server Query. That way you might be able to get the welcome message your bot sends to fewer than 1024 UTF-8 bit in size and still have the benefit of up-to-date information.

I hope one of these solutions is helpful to you :smile:

**Comment by Hakens** [comment]
Thanks for Your Replay!

I seen bot who send separated messages in once, just join on yuribot.pl and wait for bot private message, all messages send to client once, not line by line, maybe he using other api or i dont know but its possible:D

**Comment by Hakens** [comment]
Thanks for ur replay!

Can u show me ,when i need to put FloodRate.UNLIMITED this?

Regards:)

**Comment by rogermb** [comment]
Sure 😄 

Simply use the `TS3Config` object you pass to the `TS3Api` constructor and call

```java
config.setFloodRate(FloodRate.UNLIMITED);
```

I've checked out that server you mentioned. Those messages just appear to be instantaneous because there is so little delay between the single commands 😛 

To achieve similar results with this API, using the newest build with the `UNLIMITED` flood rate should go a long way. It may also help to let the query run on the same server as the TS3 server or even just a connection with a low latency / ping to your TS3 server.

**Comment by Hakens** [comment]
Thx i will check this soon,

My query bot runs on same server as the Ts3:)

Edit: Ye this Unlimited helps a lot, now its the same like on yuribot.pl

Thanks for ur time and i wish You Merry Christmas and Happy New Year!

**Comment by rogermb** [comment]
You're welcome 😄   
A Merry Christmas and a Happy New Year to you, as well!
