### ISSUE TITLE
Improve performance?

### ISSUE THREAD

**Issue by Kurimatzu** [TheHolyWaffle/TeamSpeak-3-Java-API#155]
I'm currently using this:

```
final TS3Api api = query.getApi();
			api.login("serveradmin", "");
			api.selectVirtualServerById(1);
			api.setNickname(BotName);
								
			long ms = System.currentTimeMillis();
			
			for (int i = 0; i < 1_000_000; i++) {
				api.sendChannelMessage("Bot: " + i);
			}
			System.out.println("Finished : " + (System.currentTimeMillis() - ms) + " ms");
```

However, it takes TOO much to send a message.

He's just sending a message per second, the more I want it to be faster.

Not only for the message, the performance in General (read channels, read properties from the channels etc).

You can?. Is there any setting that improves this?

**Comment by Kurimatzu** [comment]
A by placing "config.setFloodRate(FloodRate.UNLIMITED);", has improved a bit.

Moreover, it is not in your "real" performance

**Comment by rogermb** [comment]
Apart from setting the correct flood rate (and by the way, don't forget to add the IP of the query to the whitelist!), throughput has also improved massively in a recent commit.

There hasn't been a release since that commit, though, so you'd have to use a snapshot build from the [build repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.14-SNAPSHOT) to get that feature.

Duplicate of #148 and many more 😛

**Comment by Kurimatzu** [comment]
@rogermb Ok.
