### ISSUE TITLE
send ip

### ISSUE THREAD

**Issue by CrzassassinPrivate** [TheHolyWaffle/TeamSpeak-3-Java-API#156]
When i make the bot ( the java program ) make channels, add permissions or anything it allways says 
BOT ( the program nickname is BOT ) from 120.120.120.120 ( fake ip for example purposes ) is there a way to fix this? i wouldn't like my players know the server ip which the program is running on being send everywere! thanks ~crz

**Comment by somefriggnidiot** [comment]
Change the bot's display name after connecting.

**Comment by CrzassassinPrivate** [comment]
after connecting? like wait 3 seconds then set it?

**Comment by somefriggnidiot** [comment]
I may not have the best way of initiating and configuring a connection, but here's a rough approximation of my code. I put the code to rename the bot within the connection handler so that it renames any time the bot reconnects for whatever reason. (Otherwise, it could time-out and rejoin with the IP in the name once again.)

This is a snippet from within my `connect()` function.

```config = new TS3Config();
config.setHost(ip);
config.setDebugLevel(debug);
config.setFloodRate(rate);
config.setConnectionHandler(new ReconnectingConnectionHandler() {
    @Override
    public void setUpQuery(TS3Query query) {
        Api.login(queryName, queryPass);
        Api.selectVirtualServerById(id);
        Api.setNickname(name);
        Api.registerAllEvents();
    }
});

javax.swing.SwingUtilities.invokerLater(new Runnable() {
    public void run() {
        query.connect();
    }
});

**Comment by rogermb** [comment]
Or just look at *any* example in the [examples directory](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/master/example).

Most people have no need for reconnecting and multithreading stuff.
