### ISSUE TITLE
getIconId from DatabaseClient dont work

### ISSUE THREAD

**Issue by T0biii** [TheHolyWaffle/TeamSpeak-3-Java-API#158]
Hey,

if i want get the Iconid from api.getDatabaseClientbyUId("UID").getIconId(); 
i get 0
and if i get the Iconid from api.getClientByUId("UID").getIconID();
i get the correct icon id.

**Comment by rogermb** [comment]
Heyo!

I just tested this on a local server and got:

```
clientinfo clid=1
[...] client_icon_id=424599930 [...]
error id=0 msg=ok

clientdbinfo cldbid=2
[...] client_icon_id=0 [...]
error id=0 msg=ok
```

In other words: The problem seems to be caused by the TS3 server and not the API.

I found [a thread on the TS3 forums](http://forum.teamspeak.com/threads/119644-clientdbinfo-client_icon_id-is-always-0) reporting the same issue more than a year ago - seems like it hasn't been fixed yet.

If you really need to get the icons used by offline clients, you could try using `clientdblist` (`getDatabaseClients()`) and then filtering out the clients you need. This is a terrible workaround, but it might just work 😛
