### ISSUE TITLE
How to listen to client join/leave channel

### ISSUE THREAD

**Issue by lucaazalim** [TheHolyWaffle/TeamSpeak-3-Java-API#163]
Hello,

Firstly I would like to thank this API author because this is so awesome and it is helping me a lot to improve my Team Speak 3 server. That's really great!

I have a doubt about the API. Is it possible to listen to client channel join/leave? I would want to run a code when a client joins on a specific channel of my server.

I tried the TS3 Events but I didn't find these events there. I await answers, thanks!

**Comment by somefriggnidiot** [comment]
I believe the listener function you're looking for is `onClientMoved(ClientMovedEvent e)`. A `ClientMovedEvent` fires every time a client joins/leave a channel. From there, you can use `e.getTargetChannelId()` to find out which channel they moved to.

Note, however, that the person moving is grabbed using `e.getClientId()` rather than `e.getInvokerId()`. For this event, the invoker would be the person moving the client _if the client was moved by force._

**Comment by lucaazalim** [comment]
I thought that the ClientMoveEvent is called only when the person is moved by force. Thanks, @somefriggnidiot.
