### ISSUE TITLE
Issue with client permissions

### ISSUE THREAD

**Issue by zeno-vg** [TheHolyWaffle/TeamSpeak-3-Java-API#165]
When I try using the pokeClient command with the API it says it says it has insufficient permissions, but when a fresh user connects to the server they have permission to poke people. My question is how do you make the program have access to those same permissions that a default user has.

**Comment by rogermb** [comment]
Are you logging in correctly?

There's a difference between "unauthorized" client and an anonymous query. Anonymous queries have almost no permissions, especially when it comes to interacting with clients on the server.

**Comment by zeno-vg** [comment]
For the program I am using it on servers that I don't have a admin powers on, is there a way to login as a identity that is exclusive to the bot and won't be considered "unauthorized"?

**Comment by rogermb** [comment]
Yes, you usually don't have to be an admin to create a server query login. However, on some servers, normal users may not be able to create server query logins. You'll just have to try it on your server, I guess 😛 

See [here](http://www.teamspeak3.com/support/teamspeak-3-add-server-query-user.php) on how to create a login for yourself.

**Comment by zeno-vg** [comment]
After looking at my situation I see that I won't be able to make a server query login, how can I get my program recognized as a unauthorized client?

**Comment by rogermb** [comment]
"Unauthorized client" referred to an actual TeamSpeak client, not a server query.

If you can't create a server query login, you'll have to contact the admins of the server and ask for a) a login or b) the permissions to create a login by yourself. You're not able to get the required permissions on the server query otherwise.

Speaking of which, if you're creating a query that pokes clients on the server, you should have permission from the admins of the server anyways, so creating a login for you shouldn't be that much of an issue.
