### ISSUE TITLE
Can't connect and crash

### ISSUE THREAD

**Issue by Alexandre1156** [TheHolyWaffle/TeamSpeak-3-Java-API#167]
Hello,
I'm creating a Minecraft mod and I use your API.
But every time, the game crash when he try to connect to the server : 
http://pastebin.com/etZmiBD7
Here's my code : 
http://pastebin.com/gnyRuWFA
I specify that I'm not the owner of the server.
Thanks !
*Sorry if my english isn't good, i'm french ;)*

**Comment by rogermb** [comment]
You need to catch and log `TS3Exception`s if you don't want them to crash your program.

Also, the reason why you're getting this exception is because either your IP or query port are wrong, or because the TS3 server cannot be reached.

Please note that you **cannot** use some sort of "IP:port" combination as the host directly.
You need to set the IP and the query port separately by calling `TS3Config#setHost` and `TS3Config#setQueryPort` respectively.

**Comment by Alexandre1156** [comment]
I replaced the getter with a string to be sure and the error is the same. I'm sure that the IP is correct because I can connect it with the software, and he doesn't have a port.

I use characters and not numbers for the IP, do you think the error can come here ?

**Comment by rogermb** [comment]
There's a distinction between the query port and the voice port of a TS3 server. Regular clients and server query clients use different ports.

It's also possible that server query port has been deactivated or is not being forwarded on your server.

I'd try the numeric IP first. but I doubt that's what's causing the issue. Most likely it's something related to the query port.

**Comment by Alexandre1156** [comment]
Ok, I did it !
I set the query to *25639* and the ip to *localhost* and it's connect with the actual IP that the TeamSpeak 3 Client is connected, and that exactly what I wanted (I never wanted to create a bot).
Thanks anyway for your help !

**Comment by rogermb** [comment]
Glad to hear the issue has been resolved :smile:

I'll go ahead and close this thread, then.
