### ISSUE TITLE
serverIP with port

### ISSUE THREAD

**Issue by sheesh123** [TheHolyWaffle/TeamSpeak-3-Java-API#170]
hi,
when i try to connect to a server. i use the same domain that i noramlly use to connect to the server. if i want to use an IP+port (123.123.123.123:111), a error pops up instantly. why or how can i use ports?
Thanks,

**Comment by rogermb** [comment]
You'll have to set the host and port separately:

```java
TS3Config config = new TS3Config();
config.setHost("123.123.123.123");
config.setQueryPort(111);
```

Please also note that the query port is not the same thing as the voice port. I.e. the port you need to use to connect using a normal TS3 client is not the same port the query uses.

If you know the voice port of your TS3 (virtual) server and need to move the query there after you've successfully connected, use [`TS3Api#selectVirtualServerByPort`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3998).

**Comment by somefriggnidiot** [comment]
I think it's also worth mentioning that you don't necessarily _need_ the port to connect with the query. To simply connect to the server, all you need is the IP.
  
Now, selecting _your server_ (out of however many servers your host has going on that machine) is a different matter. For that, I typically use the virtual server port* to select my server. That's where the "111" comes in for your example. As Roger pointed out above, you'd use `TS3Api.selectVirtualServerByPort(111);`.
  
  
*You can also use the virtual server ID or VirtualServer (see `TS3Api.getVirtualServers()`). For most "bots," you'll likely want to use the virtual server port since it's easier for most users to find. (9987 by default, otherwise it's the number at the end of the IP they use to connect.)

**Comment by rogermb** [comment]
> I think it's also worth mentioning that you don't necessarily need the port to connect with the query

If the server is using the default query port, that is. Otherwise, this won't work.

> You can also use the virtual server ID or VirtualServer (see TS3Api.getVirtualServers()).

Yup! And if you're running a (non-commercial) TS3 server on your own, there will only ever be 1 virtual server. This virtual server also always has the ID 1, so you can simply use `TS3Api.selectVirtualServerById(1)`.

Don't try this on servers with multiple virtual servers, though 😛

**Comment by sheesh123** [comment]
ty for your answers. now i just have to find out the queryport, because the default port 10011 doenst work.

**Comment by TheHolyWaffle** [comment]
I typically use a tool like nmap to scan for open ports on a given ip when
the query port is not public. It can also just be that the query port is
hidden, preventing you from accessing it.

2017-03-14 19:27 GMT+01:00 sheesh123 <notifications@github.com>:

**Comment by sheesh123** [comment]
the owner of the server is a friend of mine, but he doesnt know the port. can i look up the port with adminpermission?

**Comment by somefriggnidiot** [comment]
I'm none too familiar with Cloudflare, but I could imagine it _could_ be an issue. If not properly configured for your server., it may be blocking query connections. If you use any TS3 monitoring tools (TSViewer, for example,) those can also help troubleshooting.

If your friend can access the server logs, there should be a line near the beginning similar to below:

> 2016-12-13 20:50:53.047052|INFO    |Query         |   |listening on 0.0.0.0:10011

**Comment by sheesh123** [comment]
I got it now. The first problem was the port. The second problem was the domain (didnt use a ip)
