### ISSUE TITLE
api.login("serveradmin", "serveradminpassword");

### ISSUE THREAD

**Issue by CharlZG** [TheHolyWaffle/TeamSpeak-3-Java-API#172]
`api.login("serveradmin", "serveradminpassword");`
Can i login using only username as anonymous client ?
or is this api intended for admins only ?

**Comment by somefriggnidiot** [comment]
Logging in would defeat the purpose of being an anonymous client. Connecting to a server starts you off as anonymous as far as I'm aware.

**Comment by rogermb** [comment]
You can also generate your own server query login in your TS3 client, provided you have the required permissions on that server.

So this really isn't just for admins: the reason why we chose the `serveradmin` account in our examples is because it is guaranteed to exist and most people want to use that account anyways (due to it having the most permissions).

**Comment by CharlZG** [comment]
is it possible to listen for incoming messages without being authenticated ? just connect and setup nickname...
