### ISSUE TITLE
onChannelDelete - not listened

### ISSUE THREAD

**Issue by PhilippMiller** [TheHolyWaffle/TeamSpeak-3-Java-API#175]
Hey I've a issue when I try to fire the _onChannelDelete_ event.

I've registered all events. All other events just work fine.
When I activate the logging (level>WARNING) it shows following:
(I've deleted 3 different channels!)

[2017-03-30 02:22:04.916] [SEVERE] TS3 command error: {msg=invalid channelID, id=768}
[2017-03-30 02:22:15.551] [SEVERE] TS3 command error: {msg=invalid channelID, id=768}
[2017-03-30 02:22:19.983] [SEVERE] TS3 command error: {msg=invalid channelID, id=768}

The real channel ids were:
51, 50 and 4.

Any idea why it wont fire?

Sincerely,
Philipp.

**Comment by rogermb** [comment]
You're getting the `invalid channelID` errors because the channels you're trying to delete have either already been deleted or have never existed to begin with. Check your IDs. If you delete a channel and create a new channel, they **won't** share the same channel ID.

As no channels were deleted, of course no event would be fired.

I've tested `onChannelDelete ` locally and - at least on my machine - everything works fine.

**Comment by PhilippMiller** [comment]
>  the channels you're trying to delete have either already been deleted or have never existed to begin with.

I delete these channel as connected client and not from a command line as bot.
So the channels are really exist and all have different channel ids 

> Check your IDs

_(see my first post)_

This is a new, clean server. And the momentary highest given channel id is 52.
So why the bot get a channel id 768

If I turned the level to ALL this will show up (the event code wont work):
```
[2017-03-30 10:15:08.801] < [event] notifychanneldeleted invokerid=1 invokername=Chuckl0r invokeruid=kPOy6QNgow8QkVY+SnMCLqS15kA= cid=6
[2017-03-30 10:15:08.803] > channelinfo cid=6
[2017-03-30 10:15:08.822] [channelinfo] < error id=768 msg=invalid\schannelID
[2017-03-30 10:15:08.822] [SEVERE] TS3 command error: {msg=invalid channelID, id=768}
```

**Comment by rogermb** [comment]
Oh, so that's what's happening!

Your `onChannelDelete` handler *does* get called when you're deleting the channel. But inside that method, you're trying to call `TS3Api#getChannelInfo` on the channel that has just been deleted.

This of course fails, because again, the channel now doesn't exist anymore.

If you need information about channels that have been deleted, you'll need to collect that information *before* the channels are deleted and store that information in a `HashMap` or similar.

This is a limitation of the ServerQuery interface and not something we can fix.

**Comment by PhilippMiller** [comment]
Oh man. Yes, sry for disturbed you.

I've found my mystace. Sry

**Comment by rogermb** [comment]
No worries man, we're here to help :smile:

This is a common pitfall, too, so I really should've recognized it immediately \^^

If you have any other questions, feel free to open another issue here. Alternatively - and a bit less formal - you can also write us over on Gitter, where we have a chatroom for this project.
