### ISSUE TITLE
isConnceted method

### ISSUE THREAD

**Issue by mlh1100** [TheHolyWaffle/TeamSpeak-3-Java-API#176]
Hey Guys.
What do you think about an isConneted method for the api. so that you can check if you connected to the Server.
Would be nice!

mlh1100

**Comment by Kakifrucht** [comment]
+1, I also feel that TS3Query should have it.

**Comment by somefriggnidiot** [comment]
Though it would be nice, what benefit does it have (other than naming) over `api.whoAmI()`?

**Comment by Kakifrucht** [comment]
whoAmI() sends a query command via not connected query, I guess that wouldn't work properly if not connected? TS3Query::isConnected would just check if the socket is opened.

**Comment by rogermb** [comment]
Sorry for taking so long to respond to this, I've been quite busy lately (and I wanted to take a bit of a Valve approach on this issue).

Lately, I've had to introduce a "connected" flag to the TS3Query anyways, so exposing this field with a getter would be no problem at all from an implementation standpoint. The thing is, the connected value doesn't really indicate whether the query is actually connected or not, as we have no way to determine this without actually sending a command. We could've lost the connection to the server almost a minute ago and wouldn't know it until the user decides to send a query command or a minute elapses and a keep-alive "whoami" is sent. So the flag is more of a "is not currently trying to reconnect" rather than a "is connected".

But still, this could all just be mentioned in the JavaDoc and I think most people would be okay with this implementation.

What I'm concerned about, though, is how people might use (or misuse) this property, and if there is a real use-case for this flag. I'm a bit concerned that people might start to roll their own reconnect systems rather than use the built-in one.

Still, if there's actually a need for such a `isConnected` method, I'd be more than happy to implement that :smile:

**Comment by Kakifrucht** [comment]
Right now there is no way to determine if the query is actually connected or not. TS3Query::exit throws a NullPointer if it didn't connect in the first place. Having a check would be more elegant. For my use case I don't really care if it is actually connected or not.

**Comment by rogermb** [comment]
> TS3Query::exit throws a NullPointer if it didn't connect in the first place.

I thought I had fixed this a while back - turns out I didn't. I'll rectify this issue asap.

> Having a check would be more elegant. For my use case I don't really care if it is actually connected or not.

Alright, I'll add a getter then :smile:

No definite ETA on this, though. It's already quite late and I won't have any (as in literally zero) spare time until Monday, maybe even Wednesday.

**Comment by rogermb** [comment]
Added isConnect method in 58b34e99527747bb53bae2d480526eb349914559.
Fixed NPE in TS3Query::exit in 0d7540268dadbf40e21da5d8926352a5a5601619.

Thank you very much for your suggestion and your further input :blush:
