### ISSUE TITLE
 How can I download PNG files via link in Java and upload them as an icon and put them to a user?

### ISSUE THREAD

**Issue by Chrissy08** [TheHolyWaffle/TeamSpeak-3-Java-API#192]

**Comment by MCelements** [comment]
```
        URL url = new URL("https://url");
        InputStream in = new BufferedInputStream(url.openStream());
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        int n = 0;
        while (-1 != (n = in.read(buf))) {
            out.write(buf, 0, n);
        }
        out.close();
        in.close();
        byte[] response = out.toByteArray();

        api.uploadIconDirect(response);
```

**Comment by rogermb** [comment]
1st question isn't really related to this API, so here's [a good answer from stackoverflow](http://stackoverflow.com/questions/921262/how-to-download-and-save-a-file-from-internet-using-java).

2nd question:
First, upload the icon to the TS3 server by using [TS3Api#uploadIcon](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4630) or [TS3Api#uploadIconDirect](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4658).
Then, modify a client's `i_icon_id` permission by using [TS3Api#addClientPermission](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L252) and set the value to the ID of the icon ID you received in the first step.

**Comment by rogermb** [comment]
And @MCelements he could just pass the `BufferedInputStream` to `uploadIcon` directly - no manual download required.

**Comment by Chrissy08** [comment]
And how can I download a PNG file from the website (https://minotar.net/avatar/yourname/16.png) and upload it as an icon? This does not work for me.

**Comment by rogermb** [comment]
Can you please be a bit more specific as to what it is that doesn't work for you? From my point of view, everything here should work together pretty well.

**Comment by Chrissy08** [comment]
The icon is not uploaded (you can not find it in the icon list)

**Comment by rogermb** [comment]
And that is after you've called `TS3Api#uploadIcon`? Did you get any error messages back?

Could you show me some of your code and maybe the communications log?

**Comment by Chrissy08** [comment]
I got noy error messages. I've used the Code from @MCelements

**Comment by rogermb** [comment]
Which is strange, because his code works. I've just added a `System.out.println` to print out the ID of the uploaded icon and I get this response in my log

```
2017-05-13 17:34:11.978 [DEBUG] [ftinitupload] > ftinitupload clientftfid=0 name=\/icon_2504834738 cid=0 cpw= size=248 overwrite=0 resume=0 proto=0
2017-05-13 17:34:11.995 [DEBUG] [ftinitupload] < clientftfid=0 serverftfid=1 ftkey=rYU2vNFu01EME1OjAU8eAREpmQ3Xf9mH port=30033 ip=0.0.0.0, seekpos=0
2017-05-13 17:34:11.996 [DEBUG] [ftinitupload] < error id=0 msg=ok
2017-05-13 17:34:11.997 [INFO] [Upload 1] Upload started
2017-05-13 17:34:11.998 [INFO] [Upload 1] Upload finished
Icon ID = 2504834738
```

And check this out, here's the icon on the server:

![image](https://cloud.githubusercontent.com/assets/1472572/26026811/d2435b52-3802-11e7-8191-7539b99f99f4.png)

This is why I don't believe that your code is running without any errors. I can only help you if you give me the information required to do so!

**Comment by Chrissy08** [comment]
Can you give me your source code? The seemingly works theirs.

**Comment by rogermb** [comment]
Again, I just used @MCelements's code, as you told me to, and added your URL and the `System.out.println` at the end:

	URL url = new URL("https://minotar.net/avatar/yourname/16.png");
	InputStream in = new BufferedInputStream(url.openStream());
	ByteArrayOutputStream out = new ByteArrayOutputStream();
	byte[] buf = new byte[1024];
	int n = 0;
	while (-1 != (n = in.read(buf))) {
		out.write(buf, 0, n);
	}
	out.close();
	in.close();
	byte[] response = out.toByteArray();
	System.out.println("Icon ID = " + api.uploadIconDirect(response));

**Comment by Chrissy08** [comment]
I've got a error message:
`[17:59:45 INFO]: [2017-05-13 17:59:45.684] [WARNING] [Upload 1] Upload failed: Connection refused: connect
[18:00:44 WARN]: Exception in thread "[TeamSpeak-3-Java-API] Keep alive"
[18:00:44 WARN]: java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/api/CommandFuture
[18:00:44 WARN]:        at com.github.theholywaffle.teamspeak3.TS3ApiAsync.executeAndReturnError(TS3ApiAsync.java:5067)
[18:00:44 WARN]:        at com.github.theholywaffle.teamspeak3.TS3ApiAsync.updateClient(TS3ApiAsync.java:4744)
[18:00:44 WARN]:        at com.github.theholywaffle.teamspeak3.KeepAliveThread.run(KeepAliveThread.java:51)
[18:00:44 WARN]: Caused by: java.lang.ClassNotFoundException: com.github.theholywaffle.teamspeak3.api.CommandFuture
[18:00:44 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[18:00:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[18:00:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[18:00:44 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:00:44 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:00:44 WARN]:        ... 3 more`

**Comment by rogermb** [comment]
The fact that you're getting a `ClassNotFoundException` means that you've not added our library as a dependency correctly.

And yes, you will have to somehow handle the IOExceptions that could be thrown by these operations.

And apart from all that, it seems like the TS3 server you're connecting to doesn't have their file transfer port opened or something along those lines. I can't really tell you why or what exactly is going on because you haven't included the relevant lines in the communications log anywhere.

**Comment by Chrissy08** [comment]
It works! The file transfer port (3306) was not open! But how do I do it, that Icon has a graphic? It is now just white and YaTQA says "Invalid stream format."

**Comment by Chrissy08** [comment]
How do I get the icon ID from the icon, what was uploaded?

**Comment by rogermb** [comment]
It's the return value of `TS3Api#uploadIcon` or `TS3Api#uploadIconDirect`

**Comment by Chrissy08** [comment]
And how I get the return value of the method?

**Comment by rogermb** [comment]
This is a joke, right? Right?

Just in case it isn't:

    long iconId = api.uploadIcon(...);

**Comment by somefriggnidiot** [comment]
Unsolicited advice: Consider using shell/skeleton/permissionless groups for icon assignment rather than assigning an icon to the user directly. This allows for easier tracking of who has that icon assigned, which is especially useful for ranks. If your use case is more along the lines of allowing users to input a URL and let your application assign that as their icon, you may want to add checks to ensure you're not having names or images collide. I'm sure most people wouldn't appreciate having 2Gb of three different icons loaded into their server... It's not fun.
