### ISSUE TITLE
How i can set a User Icon

### ISSUE THREAD

**Issue by Assassins88** [TheHolyWaffle/TeamSpeak-3-Java-API#196]
Hey,
how can i set a User Icon.
I tried to use addClientPermission but it dosnt work.
Is there an example how can i set a icon?

**Comment by rogermb** [comment]
Hi,
the method you used *should* work for setting a client's icon.

Could it be that you're using the client ID instead of the client's database ID? `addClientPermission ` requires the database ID to work.

Or maybe there's something else that causes your code to fail. In that case, I'd really appreciate you uploading some of the communications log between the client and the server and maybe even a small snippet of your code. 😄

**Comment by Assassins88** [comment]
all good it works

**Comment by bote100** [comment]
SEND CODE!!
