### ISSUE TITLE
How disable TS3 Error-Log

### ISSUE THREAD

**Issue by cherob** [TheHolyWaffle/TeamSpeak-3-Java-API#199]
I would like to log some things and if I run a teampeak command over try and catch this does not go is still an error as serial to the console output.

Either there is a possibility to disable this error message from teamspeak

Or you can forward it to another console

Or I write my schachen in another console

Or the error message is returned to the expander and can then be read out via "printStackTrace ()"

**Comment by Kakifrucht** [comment]
You are talking about command error warnings? We did discuss these already, I personally opted to log them at level debug, @rogermb and @TheHolyWaffle didn't agree. But fear not, as in the current development branch logging was abstracted, meaning you can drop in whichever logging framework you want. In order to remove TS3 command errors or send them to another stream configure the class ``SocketReader`` to only log error messages.

**Comment by rogermb** [comment]
Hi @cherob 

The next version of this API will bring improved logging support, which should let you customize what gets logged much easier, as @Kakifrucht mentioned. We'll also likely move away from returning `false`, `-1` or `null` to indicate a command error and towards using exceptions for that purpose.

In the current version, there's still `TS3Config#setDebugLevel`, which lets you turn on or off various levels of error reporting. For example, `config.setDebugLevel(Level.OFF);` will turn off all debug messages.

You also still have direct access to `TS3Query.log`, which let's you control what is logged in a more fine-grained manner.
