### ISSUE TITLE
First Move

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#201]
HI i wanna ask how i can move an Client random out of an channel to someone Other?

Like : Load.api.MoveClient(Load.api.getChannelGroupClientsByChannelId(670), clientid);

**Comment by rogermb** [comment]
Hi again,

- First of all, get a list of all clients by calling `TS3Api#getClients`
- Then, remove all clients from that list that do not fit your criteria (be it the client's channel, server group, whatever)
- After that, use `java.util.Random` to generate a random index in that list
- Finally, use `TS3Api#moveClient` to move the chosen client.

Most methods you'll need can easily be found by looking through [the Javadoc](http://www.javadoc.io/doc/com.github.theholywaffle/teamspeak3-api) or by using a search function in your IDE.

Since you've asked your questions in such a quick succession, I'd also like to remind you that the support team and I aren't here to do your programming for you. While we will answer most questions, this issues page is mostly intended for issues specific to this API and **not** general TS3 server query questions (-> TeamSpeak forums) or basic Java questions (-> Google, Stackoverflow, etc.).

**Comment by mnjg123** [comment]
@rogermb 

How do i Remove clients that are not in my channel?

-Im German sry!

**Comment by rogermb** [comment]
Use `Client#getChannelId` to check whether the IDs of the channels match.

**Comment by mnjg123** [comment]
ok thanks

**Comment by mnjg123** [comment]
@rogermb Hi i didnt get it how i can remove Clients from the list

**Comment by rogermb** [comment]
Removing an element from a list has nothing to do with this API. There is some level of Java knowledge that users of this API are expected to have.

Nevertheless, I'll link you to the [top result from stackoverflow](https://stackoverflow.com/questions/17279519/removing-items-from-list-in-java).

**Comment by mnjg123** [comment]
I know tht was an Bad Question but i cant move him

**Comment by mnjg123** [comment]
dumb*
