### ISSUE TITLE
Bot is not receiving private messages

### ISSUE THREAD

**Issue by masterstreamer** [TheHolyWaffle/TeamSpeak-3-Java-API#208]
I did like in the examples and googled a lot, the bot is reacting to the channel message, but not to the private messages to itself. Here is the code:
```
api.registerAllEvents();
api.addTS3Listeners(new TS3EventAdapter() {
        @Override
	public void onTextMessage(TextMessageEvent e) {
		int clientId = api.whoAmI().getId();
		System.out.println("Text message received in " + e.getTargetMode());
		if (e.getTargetMode() == TextMessageTargetMode.CLIENT && e.getInvokerId() != clientId) {
			String message = e.getMessage().toLowerCase();	
			api.sendPrivateMessage(e.getInvokerId(), "test");
		}
        }
});
```
The whole onTextMessage-part is not being fired if I write private to the bot.
I read this thread: https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/130
I should exit this, so I exited with query.exit() in the last line of public static void main. Is this right?
Thanks a lot!

**Comment by rogermb** [comment]
*Fixed through private messages on Gitter*

The problem was caused by having multiple server query clients logged in to the same account at once. This appears to have confused the TeamSpeak server, such that it only sent the event notifications to one of the two queries. The issue does not appear to have been caused by our API implementation.

The problem was solved by having the user create a new, separate TeamSpeak identity with which a second server query login was generated. This caused the two server queries to no longer share the same database ID and UUId, which resolved the conflict. Both query clients were then able to run concurrently.
