### ISSUE TITLE
Wrong chat

### ISSUE THREAD

**Issue by ernst-max** [TheHolyWaffle/TeamSpeak-3-Java-API#221]
Hi,

If I use the`sendPrivateMessage(targetclientID, message)`method, in some cases a chat of my client gets opened with the given message in the method instead of a chat with the bot. If the targetclient resposes to this chat, I get the testmessages. To evaluate the response, the answer has to be sent in a chat to the bot. I do not know, why in some cases a chat with my client gets opened. Do you know any reasons?

Regards

**Comment by Frigerius** [comment]
Does ur bot use ur UID? If so, create a new identity in TeamSpeak, create a query on ur Server for this UID and use ur Bot UID JUST for the bot. :)

**Comment by somefriggnidiot** [comment]
Sorry to raise this from the dead, but I see it's still sitting open and figured it could use a little more explanation. 

[JUMP TO THE FIX](#how-to-fix)

## Background
When you create your query account, it's given the Unique ID associated to the active Identity (most users only have one identity.) 
Suppose the following recipe for disaster happens:
 - The query account with UID=foobar is connected to the same virtual server as a client with UID=foobar at the same time. 
 - The query account with UID=foobar has sent a private message to a connected client. (We'll call this client 'TestUser')
 - TestUser replies to the private message.  

In this (surprisingly common) scenario, TeamSpeak gets a little confused. There are two connections sharing that unique ID. For all TeamSpeak cares, it's the same user, _just connected in two different ways._ (Query and Client.) Given all this, TeamSpeak has to make a choice: Does it pass the message from TestUser's client to FooBar's client, or does it pass the message from TestUser's client to FooBar's query? 

Naturally, it will choose to keep things between clients. It's the safest bet since your "average user" probably isn't going to be messaging a query when they could message a client if they're both the same "person."

That's where this issue stems from: You're connected with both your client and your query at the same time since the query your program is logging in with was created with the identity you use on the client.

## How to Fix
Thankfully, this doesn't take a whole lot of effort to fix. The following steps assume you want a custom identity for your query program^:
1. In the TeamSpeak 3 client, go to _Tool -> Identities_. (Shortcut: Ctrl + i)
2. On the bottom left of the Identities pop-up, click the "Create" button.
3. Select the new identity (named "New identity) that popped up at the bottom of the list on the left side of the pop-up..
4. On the top box on the right hand side ("Identity Name:") create a unique, memorable name for your query program's identity. _Note: Nickname doesn't matter; most API users set a different one within their programs._
5. Click the "OK" button on the bottom right of the pop-up.
6. Back in the TeamSpeak 3 client, go to _Connection -> Connect_ (Shortcut: Ctrl + s)
7. Enter the necessary connection information for the server you wish to create a query account on.
8. On the bottom left of the "Connect" pop-up, click the "More" button.
9. On the right side, at the top of the portion that just displayed, change the "Identity" drop-down to the identity you just created for your query program.
10. Click "Connect"  (or "In New Tab") near the bottom-right of the "Connect" pop-up.
11. With the new connection selected as your active tab, go to _Tools -> Server Query Login_ and follow the prompts to receive your new query login information.
12. Within your program (or program config) replace all references to the old query name and password with the information you just generated, and enjoy no longer receiving messages meant for your query program!

^They also assume you know absolutely nothing about navigating around TeamSpeak 3. Just to help out anyone else that may have this issue in the future.
