### ISSUE TITLE
Make Bot visible as "normal" user

### ISSUE THREAD

**Issue by repte** [TheHolyWaffle/TeamSpeak-3-Java-API#228]
I really like your project. I successfully managed to make the bot managing my server without any Server Admins needed. 

For my newest project, I am trying to make the bot "visible" like it is a normal user. At the moment users can not chat to him if the bot did not text first (private message).

My bot uses the Telegram and Steam API (users can get a list of connected users in Telegram and chat directly with them, same for Steam).

My question now is: is it possible to make the Bot visible as a Client? If not do you maybe know a solution for Java I can have a look at? Thank you

**Comment by Kakifrucht** [comment]
Afaik there is no Java solution for what you are looking for. This API only serves as a wrapper to the Teamspeak 3 query interface. Connected clients do not show up as normal users.

**Comment by somefriggnidiot** [comment]
From my understanding, this is possible, but i believe it may be against
the ToS for TeamSpeak. There are solutions that have accomplished this
(SinusBot) by running a minimal version of the client. However, I do not
know how this is accomplished.

My workaround has been to simply use my query program as a greeter so that
all users have an active chat window with it upon joining. To cut down on
spam, you could instead create a chat command that the query would respond
to.

Overall, this is not really a question for this API, as it is simply for
query connections, which will never show up as normal users. (Users can,
however, opt to display connected query clients in their bookmark settings,
but this is not something you can do for them.)

On Sep 30, 2017 6:17 AM, "Niklas Demme" <notifications@github.com> wrote:

I really like your project. I successfully managed to make the bot managing
my server without any Server Admins needed.

For my newest project, I am trying to make the bot "visible" like it is a
normal user. At the moment users can not chat to him if the bot did not
text first (private message).

My bot uses the Telegram and Steam API (users can get a list of connected
users in Telegram and chat directly with them, same for Steam).

My question now is: is it possible to make the Bot visible as a Client? If
not do you maybe know a solution for Java I can have a look at? Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/228>, or mute
the thread

**Comment by repte** [comment]
Thank you for your quick answers! I already noticed SinusBot. So far as a solution my bot will chat the users first. But after a minute or two, the chat says that my bot is not "visible" anymore and sending messages will be sent as an offline message (which gives an error). Is there a way I can guarantee the chat stays active without spamming text messages to the users?

Chat with my bot:

<18:28:08> "smart-du.com Bot": Looks like it is your first time here! Have fun and respect other people.
<18:29:25> Ihr Chat Partner ist nicht mehr sichtbar. (Translation: Chat partner not visible anymore)

**Comment by Kakifrucht** [comment]
There might be an issue with your code then. My bot only contacts the user on join (or on channel join) and it never loses connection. Do you run your bot remotely or on the same machine? Does it lose connection?

**Comment by repte** [comment]
I am running it on the same machine (connection via localhost). 
In my MAIN I am using

_TeamspeakHandler teamspeak = new TeamspeakHandler("smart-du.com Bot", "localhost", "serveradmin", "password");_

**Class teamspeakHandler**

```
public TeamspeakHandler(String botName, String host, String adminUser, String adminPW) {
		this.botName = botName;
		this.host = host;
		this.adminUser = adminUser;
		this.adminPW = adminPW;
		getApiFromTeamspeakServer();
	}
	
	public void getApiFromTeamspeakServer() {
		final TS3Config config = new TS3Config();
		config.setHost(host);
		final TS3Query query = new TS3Query(config);
		query.connect();
		final TS3Api api = query.getApi();
		api.login(adminUser, adminPW);
		api.selectVirtualServerById(1);
		api.setNickname(botName);
		this.api = api;
	}
	
	public TS3Api getApi() {
		return api;
	}
```

**Comment by Kakifrucht** [comment]
So you only ever create one TeamspeakHandler? Don't see any issues then if it can connect.

**Comment by repte** [comment]
Correct, its only called once.

**Comment by repte** [comment]
**Main.java**

```
package main;

import java.util.List;

import com.github.theholywaffle.teamspeak3.api.wrapper.Channel;
import com.github.theholywaffle.teamspeak3.api.wrapper.Client;
import com.github.theholywaffle.teamspeak3.api.wrapper.ServerGroup;

import database.DatabaseHandler;
import teamspeak.TeamspeakHandler;

public class Main {

	public static void main(String[] args) {

		// data to connect to teamspeak server
		TeamspeakHandler teamspeak = new TeamspeakHandler("smart-du.com Bot", "localhost", "serveradmin", "password");
		// data to connect to database
		DatabaseHandler database = new DatabaseHandler("teamspeak", "localhost", "root", "");

		while (true) {

			// current list of connected users
			List<Client> clients = teamspeak.getApi().getClients();

			// current list of available channels
			List<Channel> channels = teamspeak.getApi().getChannels();
			
			//current list of avaible server groups
			List<ServerGroup> srvGroups = teamspeak.getApi().getServerGroups();

			// loop to run all connected users
			for (int i = 0; i < clients.size(); i++) {
				// ignore bot user
				if (!clients.get(i).getUniqueIdentifier().equals("serveradmin")) {

					// checking if users exist in database
					if (!database.isUserInDB(clients.get(i).getUniqueIdentifier())) {
						//user not found
						teamspeak.getApi().sendPrivateMessage(clients.get(i).getId(), "Looks like it is your first time here! Have fun and respect other people.");
						database.insertUser(clients.get(i).getUniqueIdentifier(), false, false, "null", clients.get(i).getNickname(), "null", "null", "null", clients.get(i).getIp());
					} else {
						// user found in db
						database.updateUser(clients.get(i).getUniqueIdentifier(), clients.get(i).getNickname(), clients.get(i).getIp());
					}

					// getting channel ID for AFK channel
					int channelAFK = 0;
					for (int x = 0; x < channels.size(); x++) {
						if (channels.get(x).getName().equals("away from keyboard")) {
							channelAFK = channels.get(x).getId();
						}
					}

					// checking for AFK's and switching them
					// if client is away OR idle for 60min OR mic AND headset muted
					if (clients.get(i).isAway() || (clients.get(i).getIdleTime() / 60000) >= 60 || clients.get(i).isInputMuted() && clients.get(i).isOutputMuted()) {
						if (clients.get(i).getChannelId() == channelAFK) {
						} else {
							teamspeak.getApi().moveClient(clients.get(i).getId(), channelAFK);
						}
					}
					
					//check if user is admin and give/take rights
					if(database.isAdmin(clients.get(i).getUniqueIdentifier())) {
						if (!clients.get(i).isInServerGroup(6)) {
							teamspeak.getApi().addClientToServerGroup(6, clients.get(i).getDatabaseId());
						}
					} else {
						if (clients.get(i).isInServerGroup(6)) {
							teamspeak.getApi().removeClientFromServerGroup(6, clients.get(i).getDatabaseId());
						}
					}
					
					// ongoing

				}
			}
		}
	}
}
```

**TeamspeakHandler.java**

```
package teamspeak;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;

public class TeamspeakHandler {
	
	private String botName;
	private String host;
	private String adminUser;
	private String adminPW;
	private TS3Api api;
	
	public TeamspeakHandler(String botName, String host, String adminUser, String adminPW) {
		this.botName = botName;
		this.host = host;
		this.adminUser = adminUser;
		this.adminPW = adminPW;
		getApiFromTeamspeakServer();
	}
	
	public void getApiFromTeamspeakServer() {
		final TS3Config config = new TS3Config();
		config.setHost(host);
		final TS3Query query = new TS3Query(config);
		query.connect();
		final TS3Api api = query.getApi();
		api.login(adminUser, adminPW);
		api.selectVirtualServerById(1);
		api.setNickname(botName);
		this.api = api;
	}
	
	public TS3Api getApi() {
		return api;
	}
	
}
```

**Comment by Kakifrucht** [comment]
Now I see a couple of problems.
Firstly, since you run on localhost, use ``setFloodRate(FloodRate.UNLIMITED)`` on your TS3Config object before passing it to your query.

Secondly you should look into using events via ``TS3Api::addTS3Listeners()`` and ``TS3Api::registerAllEvents()`` instead of looping the way you do it, which just causes you to send an unnecessary amount of query commands to your server and maybe use a ``ScheduledExecutorService``, and pass it a Runnable that will do your AFK checks like every 10 seconds, as there are no events you could use here.

Also, is it really necessary to find the AFK channel with every iteration again and again?

**Comment by repte** [comment]
I see! Thank you for your help and tips! Will change that asap!
