### ISSUE TITLE
Check if Client is online

### ISSUE THREAD

**Issue by DieKuhMachtMuhh** [TheHolyWaffle/TeamSpeak-3-Java-API#229]
Hallo, 

I've been working with the API for a short time. Now I would like to try something.
I would like, that if someone writes to the bot with !admin <name> should look the bot if the client with the name is online and if he is online, he moved into a channel if he not online write an answer Unfortunately I do not find anything like this

**Comment by rogermb** [comment]
I'd recommend you use something like a UId to look up that client and not just their name. Anyone on the TS3 server could change their name to be identical to the admin's name otherwise.

With that UId, you could simply call [`TS3Api#getClientByUId(String)`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L2016-L2034). If the client is online, this method will return a `ClientInfo` object that also contains the client's client ID, which you could then use to move them into the same channel. If that client isn't online, this method simply returns `null`.

**Comment by DieKuhMachtMuhh** [comment]
I know, you mean:

`if(TS3Api.getClientByUId(uid) == null) {
	//offline				
} else {
	//online				
}`

**Comment by Frigerius** [comment]
Hey, I did something similar for my Bot. In my case I have a List of supporters I will notify, if someone writes "!verify". The list is dynamic and will be updated if a supporter joins or leaves the TS. If the list is empty I can simply tell the user, that there is no support. I would suggest that you can just take a look at my code, if you still need some inspiration: [https://github.com/Frigerius/Gw2FrostBot/blob/master/src/de/frigerius/frostbot/commands/VerifyCommand.java](url) The interesting part for you starts at line 88 with the call of `handleDirectCall(client);` so just take a look at the methods `private void handleDirectCall(Client client)` and `private void sendMsgToSupporter(Client client, String msg, RequestionState state)`
You will see that I just notify the supporter and don't move them directly, so the user can't abuse the system too easy ;)

**Comment by DieKuhMachtMuhh** [comment]
Thank you ^^

**Comment by rogermb** [comment]
Does this resolve your issue or do you have any other questions?
