### ISSUE TITLE
Unnecessary usage of long

### ISSUE THREAD

**Issue by 1bytee** [TheHolyWaffle/TeamSpeak-3-Java-API#233]
You should use an int [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4630) since you're casting the long to an int later on.

Also if the long is larger than Integer.MAX_VALUE there might be some errors.

**Comment by rogermb** [comment]
Nah, that's on purpose -- it's actually done to *prevent* errors.

File sizes are often provided as a `long`, e.g. [`File#length`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#length--), [`Files.size(Path)`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#size(java.nio.file.Path)). If we were to use integers in `uploadIcon`, users would likely just cast that file size to an `int` and pass it on to `uploadIcon` for small files. If a file somehow happened to be larger than 2^31 bytes, they'd possibly end up with a negative value, which would cause an exception with an error message that is likely not very descriptive.

That's why we take longs, do the overflow checking ourselves and then cast them to ints: [`FileTransferHelper#readFully`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/FileTransferHelper.java#L130) checks if the length is greater than `Integer.MAX_VALUE`.

(We may actually want to compare the value to the JVM's maximum array size and not Integer.MAX_VALUE. The problem is that the maximum array size is not in the Java specification and thus may vary from JVM to JVM. Hmm...)
