### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by minecraftkeba** [TheHolyWaffle/TeamSpeak-3-Java-API#236]
Could you check com.github.theholywaffle.teamspeak3.SocketReader for me.

I think you missed a ! in line 54.

Shouldn´t it be while(i < 4 || !in.ready()) so it waits until the reader is ready?

Thanks

**Comment by rogermb** [comment]
Hi! I checked, and this is intentional. [`Reader#ready`](https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html#ready--) does not return whether the stream is "ready", but rather whether there is data available to the stream that can be read without blocking.

The reason why we use this is because we want to skip the "welcome message" the TS3 server sends us when we first connect. Usually, this is just 4 lines of text. However, in case the server sends back a longer message (for whatever reason), we want to be able to handle this. We don't want to return part of the welcome message as the "first response" to an API command.

I hope this clears up this issue :smile:
