### ISSUE TITLE
Away toggle event?

### ISSUE THREAD

**Issue by LinXX2** [TheHolyWaffle/TeamSpeak-3-Java-API#245]
Hey, 
is it possible to create a Away toggle Event without checking in a while loop, who toggled Away since the last loop?

**Comment by rogermb** [comment]
No, I'm afraid we're not able to create new events.
That's because we're not the authors of the TeamSpeak server itself - we thus can't modify the server query interface. This API is just a wrapper around the commands and events the server query interface provides.

A polling loop, while not the prettiest implementation, is probably the only way to detect such changes on the TS server. Just make sure that there's some kind of delay in your loop (anything between fractions of a second and a few minutes) so you're not sending thousands of commands per second when using the `UNLIMITED` FloodRate setting :smile:

**Comment by LinXX2** [comment]
Okay thanks :)
