### ISSUE TITLE
 < isInServerGroup Bug! >

### ISSUE THREAD

**Issue by ali120** [TheHolyWaffle/TeamSpeak-3-Java-API#248]
hello i have problem    wen id do 	https://d.top4top.net/p_758aotla1.png

nothing  Happend  https://c.top4top.net/p_758irwpk1.png

can i get help ?

**Comment by rogermb** [comment]
Where does that magical "client" variable come from? It would really help if we could see the whole method without some of it being cut off by a TS3 permissions window 😛

**Comment by ali120** [comment]
lock at scr https://hastebin.com/iveritewab.java

**Comment by rogermb** [comment]
Here's the cause of your issue:

```java
final Client client = api.getClientByUId(event.getInvokerUniqueId());
```

This is wrong. The "invoker" is the client that *caused* that event to happen, not the client involved in the event. Since nobody can force a client to join a server, `getInvokerUniqueId` will always return an empty string for a join event.

Instead, just use the client ID you just extracted from the event object one line above:

```java
ClientInfo client = api.getClientInfo(clientId);
```

This should fix your issue.

**Comment by ali120** [comment]
thank you very very match <3
