### ISSUE TITLE
How to change Channel Name

### ISSUE THREAD

**Issue by MrCodingMen** [TheHolyWaffle/TeamSpeak-3-Java-API#263]
I don't think there's a way to change the name of a channel. When looking at the TS Query Guide, you can do a channel update.

When I do the following: 
```
final Map<ChannelProperty, String> properties = new HashMap<ChannelProperty, String>();
properties.put(ChannelProperty.CHANNEL_NAME, Data.team_online + " Teamler sind online");
Main.api.editChannel(Data.Teammitglieder_channel,properties);

```
the following error occurs in the console: 

`[2018-04-22 12:40:42.237] [SEVERE] TS3 command error: {msg=convert error, id=1540}
`
What did I do wrong?

**Comment by rogermb** [comment]
The only way I've been able to reproduce that error is by setting the channel ID (`Data.Teammitglieder_channel` here) to a negative number.
So I'd encourage you to check whether the channel ID value is in fact correct.

If that isn't the case, you should take a look at what command is actually being sent to the TeamSpeak server. To do that, you'll need to enable communications logging by calling `setDebugLevel(Level.ALL)` on your `TS3Config` object before passing that object on to `TS3Query`'s constructor. Then, everything being sent back and forth should also appear in your console log.

**Comment by rogermb** [comment]
First of all, sorry for taking so long to get back to you.

Second, this log snippet shows that the problem you're describing is not caused by that call to `TS3Api#editChannel` at all, but rather by a call to `TS3Api#getClientByUId`.

The client doesn't seem to be online, so `clientgetids` returns an error / empty response and the following command `clientinfo` command fails. If you're checking the return value of that `getClientByUId` call for `null`, you can simply ignore that log entry.

Moreover, we've since changed both our logging policies and the exact behavior of `getClientByUId`. So if you're annoyed by these log messages, there's a beta version of the upcoming 1.1.0 release available for download that you could try out :smile:
