### ISSUE TITLE
Question: Synchronous API design

### ISSUE THREAD

**Issue by glains** [TheHolyWaffle/TeamSpeak-3-Java-API#265]
I have used the API for quite some time now and i would like to ask some questions about the design. 

For example, consider the following method which is part of the synchronous API:
```java
/**
  * Gets a list of channels whose names contain the given search string.
  *
  * @param name
  * 		the name to search
  *
  * @return a list of all channels with names matching the search pattern
  *
  * @throws TS3CommandFailedException
  * 		if the execution of a command fails
  * @querycommands 2
  * @see Channel
  * @see #getChannelByNameExact(String, boolean)
  */
public List<Channel> getChannelsByName(String name) {
	return asyncApi.getChannelsByName(name).getUninterruptibly();
}
```

A typical consumer could use it like this:
```java
List<Channel> channels = bot.getTs3Api().getChannels();
System.out.println("Amount of channels" + channels.size());
```
Of course that works, as long as there are no connection issues. But what if? Well, we would get an unexpected `NullPointerException`, since the actual implementation returns `null` if the query failed. Im my opinion this is either bad design or poorly documented. I would have expected either an *empty* list or at least a hint in the documentation that warns the consumer about a nullable list.

Also, all methods in the synchronous API dont throw an exception but use some kind of return value or `null`to indicate that the query failed. This will result in losing the actually cause of the exception. However, i have noticed that the API itself is logging error messages, but its hard to track where to error actually came *from*.

But maybe you are thinking differently on this, i would love to hear from you.

**Comment by rogermb** [comment]
Nah, we pretty much agree on all of these issues 😄 
However, most of them have already been addressed:

> Of course that works, as long as there are no connection issues. But what if? Well, we would get an unexpected `NullPointerException`, since the actual implementation returns `null` if the query failed.

That's true, but only if you haven't told the query to automatically reconnect. If you're using the reconnect feature, that call will block until a new connection has been established and the command has actually been executed. But as reconnecting takes a bit more code to set up and can have some surprising side effects, it isn't enabled by default.

The reason why reconnects are so tricky is because neither the `telnet` protocol used by the TS3 server nor the TS3 server itself keep state about the current connection, so if you reconnect, you're just some new query client. That means you need to log in again, select the correct virtual server and channel, and so on. Further, there's no way for us to know whether an "in-flight" command was actually executed when the query was disconnected - the command may have been dropped on the way to the server or on the way back. So if you get disconnected while executing a `privilegekeyadd` command, you could end up creating either one or two privilege keys when the command is re-executed.

> Im my opinion this is either bad design or poorly documented. I would have expected either an *empty* list or at least a hint in the documentation that warns the consumer about a nullable list.

Agree, but I wouldn't exactly call returning an empty list intuitive, either 😜 

Throwing a exception with more information about what went wrong is the only sensible way to handle exceptional situations.

> Also, all methods in the synchronous API dont throw an exception but use some kind of return value or null to indicate that the query failed. This will result in losing the actually cause of the exception. 

That's the way it used to work in v1.0.x, yeah. In v1.1, synchronous API calls throw an exception instead of returning `null`, except in a few (documented!) places where throwing an exception just wouldn't make sense. (These methods will probably change in v1.2, too. The switch to Java 8 will allow us to use Optional, which is a perfect fit for these few edge cases.)

To come back to the original example of a connection issue: If you didn't tell the query to automatically reconnect, the method would fail by throwing a `TS3QueryShutDownException` with a message of "The query was shut down or disconnected".

> However, i have noticed that the API itself is logging error messages, but its hard to track where to error actually came from.

Somewhat tangential, logging has also improved in v1.1: If you're using Maven or a similar dependency management tool, you'll be able to choose your own logging provider which you can configure as you see fit.

The JAR file you can download from the downloads page, on the other hand, ships with SLF4J-simple as the default logging provider (i.e. the binary on the downloads page is the -with-dependencies JAR) because I don't want to get flooded with bug reports about a missing logging provider, but even that one now lets you configure what, how, and where something is logged :smile:
