### ISSUE TITLE
v1.1.0 Teamspeak3-api-1.1.0-javadoc.jar false positive in Windows Defender

### ISSUE THREAD

**Issue by MicLieg** [TheHolyWaffle/TeamSpeak-3-Java-API#267]
Chrome and the best browser (Internet Explorer) apparently find a virus in the file `teamspeak3-api-1.1.0-javadoc.jar` from the release `v1.1.0`

**Comment by rogermb** [comment]
Hmm, that's weird. We certainly didn't upload anything malicious.

Just to be sure, I ran the file through [virustotal](https://www.virustotal.com/#/url/28fe166f19668a2ae87a32c1bd13e83d6c376d54c9788acc6f1a8190881841dc/detection) - all clean. I also checked the file modification timestamps through the [GitHub API](https://api.github.com/repos/TheHolyWaffle/TeamSpeak-3-Java-API/releases/10926817), and the JAR files haven't been modified since the original release date, either.

Finally, when I download the file in both Chrome and Edge (can't test IE, I've disabled that security risk of a browser), I don't get any sort of "virus alert" beyond the standard warning that executable files can potentially be dangerous.

So this leaves me to ask, are you using some strange antivirus program that isn't in the list of programs tested by VirusTotal? Or could it be that some other program is modifying the files you're downloading?

If you want to test the file integrity, here are some hashes for the javadoc-jar you've downloaded:
- SHA1: `9d73f9b9b3ee7f19ddbe415094ec59ce37a22b86`
- SHA256: `bfd47f2fb7112c9fb41e81ae2183caffbba1f5facc093e39a96791c226cc2ff6`

**Comment by Kakifrucht** [comment]
I can confirm the issue, browser doesn't matter though, it's Windows Defender removing the file.

**Comment by rogermb** [comment]
Now that's interesting! Not sure what we can actually do about this false positive, though.

**Comment by Henny022** [comment]
som antiviruses just remove every executeable they dont know

**Comment by MicLieg** [comment]
So i didn't even manage to do download the file because it gets deleted immediately but i can confirm that its Windows defender deleting it.

**Comment by rogermb** [comment]
> So i didn't even manage to do download the file because it gets deleted immediately but i can confirm that its Windows defender deleting it.

You could turn off your antivirus for a short moment, download the file, verify its integrity, and then turn the antivirus back on.

> Maybe there is in fact something malicious in the jar file.

It's just a JAR file, aka a renamed zip file. You can extract it and look at all the files it contains. You could even let your antivirus check all extracted files as separate files. There's nothing malicious in there.

Moreover, this is a Javadoc JAR we're talking about. This archive doesn't contain executable Java classes, but just plain old HTML files. The worst thing that could possibly be in there would be some malicious javascript.

I've also let Windows Defender manually check teamspeak3-api-1.1.0-javadoc.jar, and it comes up clean on my system, so I really can't explain this behavior.

Maybe you guys have both got the Staatstrojaner? 😛

**Comment by MicLieg** [comment]
> Maybe you guys have both got the Staatstrojaner?

Hahaha paranoid level over 9000? 

But the Windows defender gotta see something it doesn't like. You probably should find the exact part which triggers the false positive (FP) so that you can change this part to get rid of the FP. I will try my best to find it later.

In the Meantime please submit the file for malware analysis at https://www.microsoft.com/en-us/wdsi/filesubmission and keep us updated :D

**Comment by rogermb** [comment]
> Hahaha paranoid level over 9000?

I was just joking :smile:

> You probably should find the part which that the false positive (FP) so that you can change this part to get rid of the FP. [...] In the Meantime please submit the file for malware analysis

Sure, but the problem is that my Windows Defender doesn't recognize anything malicious in that file, so I simply don't have the required information to make such a submission.

While we're at it, could you please make sure that your Windows Defender virus signatures are up-to-date? Mine, i.e. the ones that don't recognize the javadoc JAR, are just a few hours old.

**Comment by MicLieg** [comment]
I have tested it on 2 Up to date Windows 10 machines and both detect it. Are you sure that your Realtime protection is enabled or whatever this is called?

**Comment by rogermb** [comment]
Yeah, it's on. And even if not on the first PC, then definitely on the second one I tested.

If you disable your AV to download the file, then re-activate it and scan it manually, is the javadoc jar still detected as a threat? If so, could you please open the Windows Defender Security Center, check the detection history and tell us what the name of the detected threat was and in which file it was found?

**Comment by Kakifrucht** [comment]
It was detected as Trojan:Java/Tisifi.C, redownloading it now works without issues though. This may be because I added it as exempted file yesterday, however I don't know where I can remove it.

**Comment by rogermb** [comment]
Seems like we're not the only ones whose JAR files trigger that false positive: https://github.com/rest-assured/rest-assured/issues/1005

**Comment by rogermb** [comment]
Does Windows Defender still detect that JAR file as a threat or has this false positive been resolved?

**Comment by MicLieg** [comment]
@rogermb Yep! unfortunately yes :<

**Comment by Frigerius** [comment]
On up to date windows with BitDefender (which I think will disable Windows Defender) there is no Problem. On another system, with just updated Defender the same error occurs.
One thing I didn't try yet, since I usually don't use Windows Defender: Did you try downloading the docs using maven or gradle? (This shouldn't do any difference but hey, you could give it a try)

**Comment by rogermb** [comment]
[Version 1.2.0](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/releases/tag/v1.2.0) has just been released. @MicLieg, could you please test whether this false positive is still being triggered by the 1.2.0-javadoc JAR? 😄

**Comment by MicLieg** [comment]
Yup, still the same problem :/

**Comment by MicLieg** [comment]
#https://github.com/rest-assured/rest-assured/issues/1005

**Comment by rogermb** [comment]
Submitting the file actually worked! 😄 

@MicLieg Could you follow the instructions in the picture below and check if the Jar still gets detected? 😃 

---

![image](https://user-images.githubusercontent.com/1472572/47888207-58df3b80-de43-11e8-9fe8-9416df3f7d39.png)

**Comment by rogermb** [comment]
Judging from the lack of a negative response, I guess the JAR isn't being detected anymore 😄 

Thanks for reporting this issue to us, @MicLieg! 🎉

**Comment by MicLieg** [comment]
@rogermb 
I did what they told.
It still says `Trojan (Java/Tisifi.C)`
Yes, i have an up to date version of Windows.
Can anyone still reproduce it?
