### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by Tobias3107** [TheHolyWaffle/TeamSpeak-3-Java-API#269]
Hey Guys, Iam programming a TS3 Bot and i have sometimes some issues and i knew how to solve the problems. But sometimes it is helpful to have a Debug mode. I use the newest version. I mean it was 1.1.0. I cant find some Debug mode like the older version -> config.setDebugmode(Level); I have saw Communications logging but it doesnt change anything. I doesnt became more infos about the login about the commands or anything

**Comment by rogermb** [comment]
Hi!

Enabling communications logging should cause all messages exchanged between the client and the TS3 server to be logged. If that isn't the case, you may have a problem with the configuration of your logging provider.

Are you using Maven or did you download the API JAR from the GitHub downloads page? The reason why I'm asking is because the Maven build doesn't contain an SLF4J-compatible logging provider - you're supposed to add one as a dependency. The JAR file you can download on GitHub already contains a configured instance of SLF4J-Simple as a logging provider.

Further, are you running your TS3 bot directly by using a standard Java executable or are you using some kind of container application (e.g. a Minecraft server)? These applications may change the logging level of your application or forcefully register a different logging provider, which could result in you not seeing some of the log messages.

**Comment by Tobias3107** [comment]
Iam using a Standard Java Executable and using also Maven. You mean i musst create a *.propeties file for the configuration the Logging?

**Comment by rogermb** [comment]
If you're using the Maven build, you'll either need to provide a logging framework (e.g. Log4j 2, Logback, etc.) or just use the default implementation using slf4j-simple by using the `-with-dependencies` artifact.

To do that, you'd add `<classifier>with-dependencies</classifier>` after the "version" tag in the dependency entry in your pom.xml.

**Comment by Tobias3107** [comment]
Ok Thank you.

**Comment by rogermb** [comment]
You're welcome! 😄 

If you're having any other logging-related issues, feel free to re-open this issue.
