### ISSUE TITLE
Reconnect Strategy - statement

### ISSUE THREAD

**Issue by Tobias3107** [TheHolyWaffle/TeamSpeak-3-Java-API#272]
Hey,
Can you add statement to all Reconnect Strategy. I dont know what do what and when i have to use it.
Were be nice when you do Statements.

**Comment by rogermb** [comment]
Could you elaborate what you mean by "statement" in this context? I'm afraid I can't quite follow.

> I dont know what do what

There's a [reconnect example](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ReconnectExample.java) in the examples directory that should give you some pointers.

Essentially, `TS3Config#setReconnectStrategy` tells the query what to do when the query loses connection to the TS3 server. By default, it uses `ReconnectStrategy.disconnect()`: if the query is disconnected, it simply gives up and stops the query.

The different reconnect strategies let you control how often and after which amount of time the query will try to reconnect. The default `ReconnectStrategy.exponentialBackoff()` should work fine for most applications.

Next, you probably also need to set a connection handler using `TS3Config#setConnectionHandler`.
This handler is called every time your query is connected or disconnected.

In particular, you should do any of the setup commands that your query needs to work correctly in this handler's onConnect method instead of doing that right after `TS3Query#connect`.
This will almost certainly include selecting the correct virtual server, logging in, moving into a certain channel, setting your query's display name, and so on.

> and when i have to use it

If you have query applications that run for long amounts of time or that should always be online, or if you're dealing with a server with connectivity issues or regular restarts, you'll probably want to use the reconnect feature.

On the other hand, if your query application is rather short-lived, you almost certainly don't need to set up reconnecting.
