### ISSUE TITLE
ClientJoinEvent - Invalid ClientID

### ISSUE THREAD

**Issue by Tobias3107** [TheHolyWaffle/TeamSpeak-3-Java-API#274]
Hello Guys,
I have a problem. Everytime when a Query join and disconnect quickly. I become a error. Because i try to get the ClientInfo about him. and then do things with the Client Information. Like when the client is admin add him to a listt and send him a message when somebody join a specific channel or Check do other things with the Client information.
-- Query Join
> <23:54:45> "Unknown from **.**.***.222:43001" loggte sich in Channel "➜Eingangsbereich" ein
<23:54:45> "Unknown from **.**.***.222:43001" hat die Verbindung getrennt (disconnecting)
-- ClientJoinEvent
if(!api.getClientInfo(e.getClientId()).isServerQueryClient())
 {
          if (api.isClientOnline(e.getClientId())) {
		addAdmin(api.getClientInfo(e.getClientId()));
		doThings(api.getClientInfo(e.getClientId()));
	}
}

**Comment by rogermb** [comment]
Hi Tobias!

Due to how the TeamSpeak server query interface works, there is no way to make sure this code always executes. Essentially, it could be that by the time even your first command gets to the server, the client has already disconnected.

However, there are several ways to make this snippet of code more "crash-resistant".

- First of all, it's important to know that any method calls in TS3Api or TS3ApiAsync will result in at least one command being sent to the TS3 server. Thus, you should try to minimize the amount of times you call these methods. In particular, you could call getClientInfo just once and save the returned object:
`ClientInfo client = api.getClientInfo(e.getClientId())`
- Second, for getClientInfo to work, the client needs to be online. Thus, calling isClientOnline after having already called getClientInfo doesn't do much good.
And keep in mind that isClientOnline also only gives you a snapshot view of the server. So isClientOnline may return true, but if the client disconnects between that call and the next command, the next command may still fail.
In this situation, it might be better to just wrap that code in a try-catch and to log the error at a lower severity level.
- Sometimes, you don't even need the ClientInfo object but can instead work with just the client's database ID (which you can get from the ClientJoinEvent object in this case).
This is particularly true for the permissions and server / channel group commands - your addAdmin comes to mind.
That way, the client doesn't even have to be online for your code to execute correctly.

Finally, if your code simply gives admin permissions to **every** server query it encounters, you could also just change the permissions of the default server query server group.

I hope this helps! Don't hesitate to ask if you have any other questions :smiley:

**Comment by Tobias3107** [comment]
Yea this helps alot
