### ISSUE TITLE
Can't send Text Messages

### ISSUE THREAD

**Issue by Finnlife** [TheHolyWaffle/TeamSpeak-3-Java-API#281]
When i send a Text Message to an client or in the Serverchat. The Bot dosent do that. There is no Error or something like that.
I use the jar and not Maven. Here the Easy Code: https://pastebin.com/PUqBM3kt
Can Somebody helps me?
Could the Problem be the Server?
The Server Version is Linux/3.3.0

**Comment by rogermb** [comment]
You need to create and modify the `TS3Config` object before passing it to `TS3Query`'s constructor. After that, there's no reason to hang onto that `TS3Config` object.

i.e. first try

```java
public static TS3Query query;
public static TS3Api api;

public static void main(String[] args) {
    TS3Config cfg = new TS3Config();
    cfg.setHost("127.0.0.1");
    [etc...]

    query = new TS3Query(cfg);
    query.connect();

    api = query.getApi();
    [etc...]
```

If that doesn't solve your issue, turn on communications logging `cfg.setEnableCommunicationsLogging(true)` and report back with that comms log :smiley:

**Comment by rogermb** [comment]
And you're sure that you're connecting to the same TS3 virtual server with both your client and your server query? Because just by looking at the communications log, it seems that all commands are executed without any issues. You're even getting event notifications about these messages back from the server.

When editing your bookmarks in your TS3 client, there's a checkbox called "Show ServerQuery Clients". If you check that checkbox and re-connect to your server using that bookmark, you should now see any online server query clients. If your client doesn't show up when you run your program, you're most likely not on the same server 😄

**Comment by Finnlife** [comment]
Yes im sure, because when i use not the Serveradmin account, its working! 
And the Function from Teamspeak with Serverquery-Clients only works with other Accounts, (Not serveradmin)

**Comment by rogermb** [comment]
Well at least on my machine, it also shows the serveradmin account:

![image](https://user-images.githubusercontent.com/1472572/43924933-20998f78-9c26-11e8-8176-b3cc6d62edb1.png)

(Tested on the newest client version and the 3.3.0 server version on Windows - but I'm almost certain that's neither a new nor an operating system dependent feature)

**Comment by Finnlife** [comment]
By virtue of you,re Message i reinstalled my Client and now the Bot ist working. But i dont now why. Because other useres have the same Problem. But the Admin-Ouery are not visible. Thank you fpr the Support

**Comment by rogermb** [comment]
Huh, strange. At least it's working now, I guess 😄 

Closed
