### ISSUE TITLE
Error when i tried to connect to the query

### ISSUE THREAD

**Issue by Mihawka** [TheHolyWaffle/TeamSpeak-3-Java-API#282]
Hi,
Ts3Server version: 3.3.0
Java 8

My problem is when i execute my code i have an error for invalid loginname or password but i'm sure i don't have make a mistake in my code. I have a theory. Recently i have upgrade my Ts3Server to 3.3.0 and since i have this error. I think than this api is not longer compatible with the new version of Ts3Server.

Make Login:
![image](https://user-images.githubusercontent.com/18295323/44120714-8bf7e71a-a01d-11e8-941f-fbdf0300d374.png)

Error:
![image](https://user-images.githubusercontent.com/18295323/44120727-9e4d010c-a01d-11e8-9782-bd86afb709b8.png)

My code:
![image](https://user-images.githubusercontent.com/18295323/44120575-151d597c-a01d-11e8-9528-411aeb9f050e.png)

**Comment by Mihawka** [comment]
Hey, 
I have remake password and login and it's doesn't work :(

**Comment by rogermb** [comment]
Hmm, I'm starting to run out of ideas here 😅 
(If anyone else who gets this notification has any ideas, please let me know!)

- If your TS3 server is hosted by some 3rd-party company, could it be that you're not selecting the right virtual server when you call `ta.selectVirtualServerById(1)`? If you know the voice port of your server, you might want to try out `ta.selectVirtualServerByPort(voicePort)`.
- Can you make sure (and by that I mean: test) that you're actually connecting to the same TS3 server that you created that server query login on?
- And if the two ideas above don't work, could you try creating a server query login and connecting with a server query on a *different* server? To do that, you could download and set up a TS3 server on your own machine. The reason I'd like to test this is because I need to know whether the logins just don't work on that specific server, or if they don't work on *any* server.

Sorry for how troublesome this troubleshooting session is, but this is a really unusual issue 😄

**Comment by rogermb** [comment]
Closed due to inactivity.
