### ISSUE TITLE
Wie kann man Channel mit Rechten erstellen ?

### ISSUE THREAD

**Issue by Finnlife** [TheHolyWaffle/TeamSpeak-3-Java-API#290]
Gibt es dazu eine Einstellung oder muss man den Channel kopieren?

**Comment by Frigerius** [comment]
To set a channels permissions you first have to create it and afterwards you can set them via the api.
Example: https://github.com/Frigerius/Gw2FrostBot/blob/806cdc9b36b8aeb607a8f8cac7a7b94829a933cb/src/main/java/de/frigerius/frostbot/ChannelController.java#L35
Maybe some methods have changed since I didn't update my Bot for month. But the procedure should be the same. Create a new Channel -> get its ID -> set its permissions

**Comment by rogermb** [comment]
First of all, please use English in these public channels.

Second, there's no way to create a channel with permissions in one command. There's also no command to copy channels. If you want to "buy time" to edit a channel's permissions after its creation, you could create the channel with the maximum client count set to 0, e.g.:

```java
Map<ChannelProperty, String> properties = new HashMap<>();
properties.put(ChannelProperty.CHANNEL_FLAG_MAXCLIENTS_UNLIMITED, "0");
properties.put(ChannelProperty.CHANNEL_FLAG_PERMANENT, "1");
properties.put(ChannelProperty.CHANNEL_MAXCLIENTS, "0");
int cid = api.createChannel("Your Name Here", properties);
```

After that, you could edit the channel's permissions using the `addChannelPermission` method. When you're done, use the `editChannel` method to set the maximum client count to some larger value or to set the unlimited clients flag back to "1".
