### ISSUE TITLE
Socket can time out if command is sent

### ISSUE THREAD

**Issue by Starmixcraft** [TheHolyWaffle/TeamSpeak-3-Java-API#291]
the socket can time out after the command is sent, this is a bug report, following my befor reported random timeouting of the socket, in https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/285 that is still not fixed, and still spamms my error log :(, please fix this bug, its realy annoying

**Comment by rogermb** [comment]
Yeah, sorry about that, I currently really don't have any time to work on this API.

The bug is fixed in the current snapshot version of the API. If you're using Maven, you could add the Sonatype snapshots repository (https://oss.sonatype.org/content/repositories/snapshots/) as a repository and set the required version of this API to `1.2.0-SNAPSHOT`.

If you're not using maven, you can download the latest snapshot [directly from the snapshots repo](https://oss.sonatype.org/content/repositories/snapshots/com/github/theholywaffle/teamspeak3-api/1.2.0-SNAPSHOT/teamspeak3-api-1.2.0-20180925.184230-8.jar).

**Comment by rogermb** [comment]
Should be fixed in [v1.2.0](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/releases/tag/v1.2.0).
