### ISSUE TITLE
Cant get client online time

### ISSUE THREAD

**Issue by Starmixcraft** [TheHolyWaffle/TeamSpeak-3-Java-API#293]
I tryed to give clients that are more then 24H online a rank but the online time is allways -1 my current code is this:

    	List<Client> clients = this.getTs3Api().getClients().getUninterruptibly();
		     for(Client client : clients) {
			if(client.isServerQueryClient()) {
				continue;
			}
			if(client.isInServerGroup(128)) {
				continue;
			}
			int connectiontime = client.getInt(ClientProperty.CONNECTION_CONNECTED_TIME);
			System.out.println(client.getNickname() + " is online for " + connectiontime);
			if(connectiontime > 60*60*24) {
				this.getTs3Api().addClientToServerGroup(128, client.getDatabaseId());
			}
		}

The quarry is connected and can send commands, also no errors in the logfile

**Comment by rogermb** [comment]
Well, that kind of stuff happens if you try to manually use `getInt(Property)` instead of using our getters 😛 

In all seriousness - the reason that doesn't work is because the TS3 server doesn't send you any value called `connection_connected_time` when using the `clientlist` command (aka `TS3Api#getClients()`).

If you **really** want to use `connection_connected_time`, you need to call `TS3Api#getClientInfo(int)` for each of your clients and then use the `getTimeConnected()` getter, which returns how long the client has been connected for in milliseconds.

But I think there's a better alternative: Just use the `Client#getLastConnectedDate()` getter. That returns a timestamp of when the client joined your server. Using Java's new time libraries, you could do something like:
```java
for (Client client : api.getClients()) {
	if (!client.isRegularClient() || client.isInServerGroup(128)) continue;

	Instant joined = client.getLastConnectedDate().toInstant();
	Instant oneDayLater = joined.plus(Duration.ofDays(1));

	if (Instant.now().isAfter(oneDayLater)) {
		api.addClientToServerGroup(128, client.getDatabaseId());
	}
}
```

Also, please be aware that both of these just track the online time for **one connection**. If the client leaves the server and later returns, both of these are reset to 0!

**Comment by Starmixcraft** [comment]
Well, that's clear, I'm an idiot, thank you for your help

**Comment by rogermb** [comment]
You're not an idiot - I think it's a fair assumption that calling `getInt(ClientProperty)` on a client should work. But thanks to how TS3 works, that's unfortunately not the case.

Good luck with your server query bot! 😄
