### ISSUE TITLE
TS3Listener for complaints

### ISSUE THREAD

**Issue by stephan-strate** [TheHolyWaffle/TeamSpeak-3-Java-API#303]
Is there a way of being notified when someone submits a new complaint?
You could check for new complaints frequently, but it would be amazing if there were a handler for this.

Currently there is no way to do that, right? It is written to the server log, so it might be
possible to add a handler for this?

**Comment by rogermb** [comment]
We're stuck with the event types that TS3 offers to us. This API is just a wrapper around their server query interface. All existing TS3 events - both the documented and the undocumented ones - have a method in [this interface](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/TS3Listener.java).

If you need more event types, you'll have to ask the TeamSpeak dev team 😄

**Comment by rogermb** [comment]
And yeah, the solution you'll have to implement will consist of repeatedly getting the list of complaints on the server using [`TS3Api#getComplaints()`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/9efd437dffe2ff0408d515609b4d9ec36398f266/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1980-L1993) and then waiting for some period of time, e.g. 1 minute 😃

**Comment by stephan-strate** [comment]
Thanks for the fast answer. Really unfortunate, that this kind of stuff does not
get pushed into the socket...
Do you have any experience on how expensive it is to get the complaints? Can I get them
every few seconds?

**Comment by rogermb** [comment]
How much data there is depends on how many complaints there are at any given time. If you want to use the complaints system in a way where there are only a handful (< 100) complaints at any time, then getting a list of complaints every second or so really shouldn't be a problem. If what you're trying to do involves a massive amount of complaints, especially ones with long messages attached, it may be a good idea to scale back a bit.

If you're on the same machine (i.e. connecting to `localhost`), the network won't be an issue (because there is none), so you could even check multiple times per second. From the small-scale tests I've done, a single `complainlist` command seems to take less than a millisecond to execute, but that obviously again depends on how many complaints there are.

In general, if you want to check more than around 3 times per second, you'll have to use the `UNLIMITED` flood rate setting. If you're not connecting from the same machine, that also means that you'll need to add the IP of your server query application to the whitelist of the TS3 server 😃

**Comment by Frigerius** [comment]
What I would think about is, do you rly need to be updated each second? Wouldn't a minute be enough? What I did for my bot was to just check for complains, if a supporter joined the server, to update him. And since I wanted a more complex ticket system, I just implemented my own one with chat commands and a database.

**Comment by stephan-strate** [comment]
> What I would think about is, do you rly need to be updated each second? Wouldn't a minute be enough? What I did for my bot was to just check for complains, if a supporter joined the server, to update him. And since I wanted a more complex ticket system, I just implemented my own one with chat commands and a database.

I am going to implement a votekick mechanism with the complaint system.
Tried several other approaches, but this came out as the best one.

I do not want users to switch the channel, to start a votekick.

> How much data there is depends on how many complaints there are at any given time. If you want to use the complaints system in a way where there are only a handful (< 100) complaints at any time, then getting a list of complaints every second or so really shouldn't be a problem. If what you're trying to do involves a massive amount of complaints, especially ones with long messages attached, it may be a good idea to scale back a bit.
> 
> If you're on the same machine (i.e. connecting to `localhost`), the network won't be an issue (because there is none), so you could even check multiple times per second. From the small-scale tests I've done, a single `complainlist` command seems to take less than a millisecond to execute, but that obviously again depends on how many complaints there are.
> 
> In general, if you want to check more than around 3 times per second, you'll have to use the `UNLIMITED` flood rate setting. If you're not connecting from the same machine, that also means that you'll need to add the IP of your server query application to the whitelist of the TS3 server 😃

Thanks for your help!

**Comment by rogermb** [comment]
You're welcome! Good luck with your votekick bot 😄
