### ISSUE TITLE
API can't set nickname

### ISSUE THREAD

**Issue by EscolarProgramming** [TheHolyWaffle/TeamSpeak-3-Java-API#317]
After updating our TeamSpeak server from version 3.5.0 to 3.7.0 the API can't set the nickname anymore. 
The exact error is:
https://gist.github.com/EscolarProgramming/818eeb5a117e37b2cbceb6bcc49c1437

Line 146 is `api.setNickname(nickname);`

We are running on API version 1.2.0

**Comment by rogermb** [comment]
Hi!

Yeah, this seems to be some weird TS3 v3.7.0 issue. It's almost as if it doesn't correctly free up the list of usernames in use when a query client disconnects.

There's no proper fix for this, but as a workaround, you could change your nickname to some different name immediately before calling `TS3Query#exit()`. That way, your nickname won't be in use the next time you connect.

Also, it looks like you're missing a SLF4J-compatible logging framework 😄

**Comment by EscolarProgramming** [comment]
Okay, thanks for that information :)
Is there a disconnect-event or something like that so I can realize a namechange immediately before the server stops (or the query disconnect)?

I'm using my own logger but I added now the SLF4J Logger :P

**Comment by rogermb** [comment]
> Is there a disconnect-event or something like that

No, I'm afraid there isn't. Then again, I can't imagine that you're calling `TS3Query#exit()` from too many different places 😄

**Comment by EscolarProgramming** [comment]
Ooops, sorry, I've missunderstood your first message 😄
Thank you, I will add that feature.

**Comment by Galileon-venta** [comment]
I've just put a try catch block around it:

`try{
            api.setNickname("NameHere");
        }catch (Exception e){
        }`

**Comment by rogermb** [comment]
@Galileon-venta I mean, that'll just leave your nickname unchanged. I'm not sure if that's really such a good idea.

I just thought of something: You could also set your nickname twice when connecting. First with a "throwaway" nickname (e.g. RealNickname-Connecting), then with the real nickname you wanted to use in the first place.

But yeah, I'm still none the wise why this issue exists. If the query disconnects without any issues, the nickname should get freed up on the server. I have no clue why this isn't happening...

**Comment by Galileon-venta** [comment]
@rogermb in my current Setup (bot and Ts-Server) it just keeps the Name...
I've created an Identity for the Bot and the Server seems to remember its name... However Bot joins with Name again without name beeing set via api.setNickname

I stopped wondering why... Reason: It's Teamspeak 🤦‍♂️

**Comment by rogermb** [comment]
Oh, here's an idea: in TS3 v3.7.0, they stopped appending the server query's IP to the end of their nickname.
So could it be that you're trying to set the nickname to the same nickname that the query already has?
"Changing" your nickname to the same nickname you already have would cause that exact `nickname is already in use (ID 513)` error.

Also...

### Recommended workaround:

Instead of using `api.setNickname(name)`, use either `api.selectVirtualServerById(id, name)` or `api.selectVirtualServerByPort(port, name)`.

Those overloads of `selectVirtualServer` also set your nickname, but they seem to be a bit smarter at it than `setNickname`, so they don't cause exceptions for no reason.
