### ISSUE TITLE
setClientChannelGroup wont work

### ISSUE THREAD

**Issue by ThisIsMac47** [TheHolyWaffle/TeamSpeak-3-Java-API#33]
As you want see http://screencloud.net/v/5z00 : i create a channel and move the player in, and grant him channel admin, my player be moved in the new channel but without the channel admin.

**Comment by TheHolyWaffle** [comment]
Enable debug and show logs.

2015-02-20 19:21 GMT+01:00 ThisIsMac47 <notifications@github.com>:

**Comment by ThisIsMac47** [comment]
http://pastebin.com/f3U8MC6f here there are

**Comment by ThisIsMac47** [comment]
it show an error : [20:39:52] [SocketReader/INFO]: [DEBUG] [setclientchannelgroup] < error id=512 msg=invalid\sclientID
But i dont understand why because i use the same method to get upside and its work so i supposed its a bug ?

**Comment by ThisIsMac47** [comment]
I have changed and use a variable to be sure that not come from my code : http://screencloud.net/v/iZOJ and it still doesnt work

**Comment by Firedroide** [comment]
The method you're using, .setClientChannelGroup, requires the client database ID, not just the client ID.

To clarify, TS uses 3 separate ID systems for clients:
- "Session" IDs: Identifies a client while they're online, but may change when a client disconnects.
- Database IDs: These IDs persist and are used for the permission system. A new ID is generated when the client first joins the server and is then saved in the permissions database. Resetting the server's permission could reset all database IDs, however.
- Unique IDs: Whatever happens, these should never change for a client, afaik.

So, to get the database ID, you need to use Client(Info).getDatabaseId() instead of .getId().

I'm still working on some javadocs for all these methods which should help explain that stuff better.
