### ISSUE TITLE
Question: How to use isEmpty()

### ISSUE THREAD

**Issue by CookieArmy** [TheHolyWaffle/TeamSpeak-3-Java-API#344]
Hello,
I just want to ask how i can use the isEmpty() / isFamilyEmpty() method.

**Comment by LinuxClient** [comment]
Hello,

which isEmpty method do you mean?

**Comment by CookieArmy** [comment]
from here:
https://javadoc.io/static/com.github.theholywaffle/teamspeak3-api/1.1.0/src-html/com/github/theholywaffle/teamspeak3/api/wrapper/ChannelInfo.html#line.88
the method from the bottom.


public boolean isFamilyEmpty() {
                return (getSecondsEmpty() >= 0);
        }

**Comment by rogermb** [comment]
`isEmpty()` indicates that the channel itself does not contain any clients, but any of its sub-channels could still contain clients.

`isFamilyEmpty()` indicates that the channel and all of its sub-channels does not contain any clients.

Unfortunately, due to how the server query API works, only some of these methods are available to `Channel` and `ChannelInfo` :/

**Comment by CookieArmy** [comment]
And how can i use the isFamilyEmpty() method?
