### ISSUE TITLE
Send private message says Invalid Client id

### ISSUE THREAD

**Issue by DevJoey** [TheHolyWaffle/TeamSpeak-3-Java-API#348]
> Issues on Github are (mostly) meant for bug reporting and feature requests. For basic questions, please use our [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) instead.

> For bug reports, please include the debug log without any private information (login, etc.) by [enabling communications logging](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API#ts3config-settings) and ensuring that ``DEBUG`` messages are being logged (enabled if you use the jar file, [see here if you use Maven](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API#download)).

If i send a private message, it works randomly. And it say invalid clientid error

**Comment by TAXSET** [comment]
Can you give us a snippet of your code so we can see what you're doing?

From memory, I can remember that (at least on our Teamspeak server), there are some "crawler queries" connecting for just a split second, so that the sendPrivateMessage() command can not complete in time before they already disconnected. And due to the client already being disconnected once the command finished, it can't resolve the clientId, which causes an exception.

One way to solve this issue is to catch any exceptions which are caused by this "limitation".

**Comment by TAXSET** [comment]
If you need an example, one of the Teamspeak Query Plugin Frameworks plugins probably suffered from the same issue. You can take a look at it here: https://github.com/Teamspeak-Query-Plugin-Framework/tsqpf-plugin-welcomemessage

**Comment by rogermb** [comment]
See #350
