### ISSUE TITLE
Player's receiving 2 double messages/pokes

### ISSUE THREAD

**Issue by OhCreative** [TheHolyWaffle/TeamSpeak-3-Java-API#36]
I am using api.pokeClient(); and every time I use it, it is posted twice. Is this a bug or something I'm missing?
![image](https://cloud.githubusercontent.com/assets/6810072/6565673/4ab70ab4-c688-11e4-9f7a-ce1319adac16.png)

code:
 public void onClientJoin(ClientJoinEvent e) { api.pokeClient(e.getClientId(), "Welcome to Lethal Darkness!"); }

**Comment by TheHolyWaffle** [comment]
the event is sent twice, one from the servers perspective and one from the
channel I believe.

2015-03-09 23:48 GMT+01:00 Brandon <notifications@github.com>:

**Comment by Firedroide** [comment]
Wow, I just got sniped!

Jup, that's the issue. And an annoying one, too. One that the implementations shouldn't have to deal with this, but rather the API should fix.
I think we should deal with this because a) the double events are not useful for the event listeners, b) they cause numerous bugs and c) due to a recent change to registerAllEvents(), these double events will occur even more commonly.

(registerAllEvents() now listens to *all* channel events and every time a client moves from one channel to another, two events are fired, too.)

Quick & easy fix would be to have a String variable "lastEvent" in SocketReader and to only fire an event if (!line.equals(lastEvent)). 

Shall I go ahead and implement this fix?

**Comment by TheHolyWaffle** [comment]
Sure, but keep in mind that not everyone subscribes to both channel and
server events. So if they only use one it should still work.

2015-03-10 16:49 GMT+01:00 Firedroide <notifications@github.com>:

**Comment by Firedroide** [comment]
You have a good point there, but I don't think it will be an issue.
My primitive fix would indeed also filter out text messages that were sent twice in a row, so I need to only apply the filter for join, quit and channel move events.

For these events, duplicates can be filtered out without having to worry about the "client did something twice in a row" case. A client can only join once, and before he could ever re-connect to a server, a quit event would be sent. Same goes for the quit event, because a client can only ever leave the server once. The channel move event will also never create the same event for the same client twice, because a client must always move to a different channel (so the notify message will differ). This applies to both the case where the client subscribes to the channel events of a specific channel or to all channel events.

What is more, it will always be the first event that is broadcast to the event listeners and a possible second event notification that is filtered out. So it won't matter if one subscribes to channel events, server events or both - they'll always get just one notification.

**Comment by Firedroide** [comment]
Your issue should be fixed now.

If you want to test it out, either clone / download the project and compile it by yourself or use a [pre-compiled version](http://ci.stutzfam.ch/job/TeamSpeak-3-Java-API/5/).

(I've set up a project on a Jenkins server real quick that automatically builds this API so we can test bleeding-edge builds easier)

**Comment by TheHolyWaffle** [comment]
Take a lookat https://jitpack.io/, it's like hosting a maven repository without the hassle of pushing it to a server. It's all based on git tags. Also appveyor might be handy.

**Comment by Firedroide** [comment]
The problem I see with jitpack.io is that it only builds only commits marked with tags and doesn't just build the project every time a commit is pushed, basically failing to do what CI is supposed to do.

AppVeyor looks very nice, but it seems to be centered around building .NET applications. While I saw that they had a JDK, Git and Maven set up on their build servers, I doubt that they'd have a Maven repository somewhere. Still some question marks there. So basically, if we go for AppVeyor, we'd still need to have a server running a Maven repository somewhere so developers could actually get the compiled jar files via Maven.

**Comment by TheHolyWaffle** [comment]
That is what jitpack is for. If you decide that the latest build is ready
for everyone than just tag it, simple. No need to host a maven repo because
they do it for you. Anyway, we could also use sonatype for the official
free open source project maven repo but they require some information
before they allow you.

2015-03-10 21:40 GMT+01:00 Firedroide <notifications@github.com>:
