### ISSUE TITLE
Problem with TeamSpeak Server Update to 3.13.2

### ISSUE THREAD

**Issue by kreidlerflorett** [TheHolyWaffle/TeamSpeak-3-Java-API#378]
I have had the problem since the TeamSpeak Server Update to 3.13.2 that the function "getChannelClientPermissions" no longer works. If I use the debug function of my code editor I only see, that in the "List<Permission" the value null is stored.

Thanks for your help!

**Comment by rogermb** [comment]
Hi. Sorry about the insane delay, I haven't really had time for any open-source work in almost a year. Feel free to ignore this issue if you no longer care about this issue.

I just updated to TS3 server version 3.13.3 myself, and the "getChannelClientPermissions" still works without any issues on my machine. I read on the TS3 forum that for some people, this update failed to migrate the TS3 database. This may have been the reason for the method failing in your case.

Either way, if this issue is even still persists, please send me the error message you're getting, as well as the code you're using to query the channel client permissions.

**Comment by kreidlerflorett** [comment]
Hello
Thank you for your reply. In the meantime I have adjusted the code so that I don't need the function "getChannelClientPermissions" at all.
