### ISSUE TITLE
Question ClientLeaveEvent

### ISSUE THREAD

**Issue by JulianRecke** [TheHolyWaffle/TeamSpeak-3-Java-API#38]
Hey,

is there a way to get the UniqueID or the DatabaseID from the ClientLeaveEvent?

**Comment by Firedroide** [comment]
No, these parameters are not transmitted with the event notification.

What you could do would be to have a HashMap in your event listener that maps the clients IDs to their UIDs (or database ID). The UIDs and database IDs are transmitted when a client first joins the server @ ClientJoinEvent.
You could then get the UID from the map by calling the remove method when the client leaves again.

**Comment by JulianRecke** [comment]
Thanks, I'll do that.
Another problem: The join and leave are triggered twice.
Am 17.03.2015 10:27 schrieb "Roger Baumgartner" <notifications@github.com>:

**Comment by Firedroide** [comment]
This was already mentioned in #29 and #36 and was fixed in 06c9785b6152b8a57ee3eab7832022433467915c.

There has not yet been an official release since this commit, and we do not (yet) have an automated build server set up for snapshot builds, so if you're just using maven, you're out of luck ^^

You could however, if you're using git, add this project as a git submodule. It's not an optimal solution as you'd probably compile this whole API every time you re-compile your project, but it would work.
