### ISSUE TITLE
getInvokerName returns an empty string

### ISSUE THREAD

**Issue by Matthbo** [TheHolyWaffle/TeamSpeak-3-Java-API#43]
The ClientLeaveEvent's  getInvokerName() returns an empty string.

**Comment by Firedroide** [comment]
ClientLeaveEvent seems to be the only event for which the TS server does not send us any information about the client who actually left. A typical *notifyclientleftview* notify message looks like this:

    notifyclientleftview cfid=1 ctid=0 reasonid=8 reasonmsg=Disconnect clid=5

As you can see, there's no invokername or anything like that in there. So basically it's this: We cannot give you information we don't have ^^

We do realize that ClientLeaveEvent still provides getters for these inexistent values and this will be "fixed" in an upcoming API update.

If you need more detailed information about your clients when they leave, you currently have to set up some kind of client registry. Basically you'd create a HashMap mapping the clients' IDs to their data. Then, when a client leaves, you could use their client ID to look up their last known nickname.

If this is something you'd like to see fixed *properly*, go complain to the TeamSpeak developers :wink:

**Comment by Firedroide** [comment]
Actually, I was wrong. `notifyclientleftview` **does** sometimes contain `invokername` and `invokerid`, and that is when there is actually an invoker, so if the event is caused by someone other than the client - i.e. when someone is kicked or banned.

Hence, no changes to the API will be made. I will, however, add some information in the form of JavaDocs.
