### ISSUE TITLE
Command Delay

### ISSUE THREAD

**Issue by exylian** [TheHolyWaffle/TeamSpeak-3-Java-API#46]
Is it normal that the commands will be delayed? 

Case: When I add a listener to a Channel and a client join this channel the bot should create a new Channel for the User and  move him into the new one. This takes about 15 seconds which is definitly to long...

Is this delay normal?

**Comment by TheHolyWaffle** [comment]
Find out what exactly is taking so long. Is it the event itself that is
slow? Or is it the creation of Channel?


2015-06-03 17:56 GMT+02:00 exylian <notifications@github.com>:

**Comment by Firedroide** [comment]
It would be great if you could give us two things so we could narrow down the root of the problem:

1. The code that deals with the TS3 query
1. The debug log in your console.

You could, for example, create a [gist](https://gist.github.com/) of these.
However, please remove the IP of your TS server and your logins from both of these files.

**Comment by Kakifrucht** [comment]
How long is the "default" api delay via Telnet on localhost not limited connections? Because there certainly is some delay.

**Comment by Firedroide** [comment]
If you're using `FloodRate.DEFAULT`, which is the default setting, each command should take about 350 millisecond, plus 2 times your ping to the server. If you're using `FloodRate.UNLIMITED`, each command should take 50 milliseconds plus ping.

The 350 millisecond default timeout between commands prevents you from being flood-banned from servers where your IP is not in the query whitelist. The 50 millisecond timeout with the unlimited flood rate is also intentional. It was put in place so servers won't be spammed with commands as easily.

There was an issue with the 1.0.12-SNAPSHOT builds (so everything newer than the last official release, 1.0.11) that made it that if you ran commands from an event listener synchronously, it would take up to 4 seconds or whatever your command timeout was for the commands to complete.

This issue has only been resolved today, so using a newer jar from our [MacGyver Maven repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.12-SNAPSHOT) should fix this, if this was actually your issue.

**Comment by Firedroide** [comment]
Just out of curiosity, @Kakifrucht, how much command delay do you experience?

**Comment by Kakifrucht** [comment]
Not much, around telnet calls in total not more than a second. I was just wondering if there is a possibility to not have any delay at all, at FloodRate.Unlimited

**Comment by Firedroide** [comment]
We'll have to discuss this internally and also check whether there any restrictions server-side. I for one just really don't see why someone would need to send more than 20 commands per second.

**Comment by exylian** [comment]
Okay the delay does not comes from my Internet Connection. I ran the bot on the same machine as the server runs.

Well the code is just experimental until now but here ist the Main Class

https://gist.github.com/exylian/c027249bca13e6e7b980

Floodrate is also set to unlimited.

**Comment by Firedroide** [comment]
It's very likely that this is caused by the bug I fixed yesterday, assuming you're running a build newer than 1.0.11. If this is the case, simply updating to the newest version should do the trick.

**Comment by exylian** [comment]
Okay I'll try it when I'm back home. I'll give you feedback in here!

**Comment by Firedroide** [comment]
Wonderful, nice to hear it works now! :D

**Comment by Kakifrucht** [comment]
Have you made any delay optimizations on the latest build since the 1.0.11 release?

**Comment by Firedroide** [comment]
No "optimizations" were made to how commands are sent. There should not really be any delay in that anyways - you're more or less guaranteed that you can send a command every 50 or 350 ms respectively.

It was, however, changed how responses from the server are read. There used to be a default waiting time of 50 ms between each response. So if there was a lot of activity on the server and you registered the query to receive all events, the incoming queue would get flooded; especially if you were using the UNLIMITED flood rate setting. Another example: If you were to send a "whoami" command to the server, it would take ~25 milliseconds on average to read the first response, i.e. the data about you and then another 50 ms for the server confirmation that no error had occurred.

This delay was cut out completely, as it really didn't do anything apart from causing annoyance. Due to this change, the delay on all command has been reduced by 25 ms on average or even more in some cases.

**Comment by Kakifrucht** [comment]
So if I update the API I can expect improvements, nice. It was not really an issue for me, but I guess faster is always better.
I thought that the FloodRate setting decided how many commands the bot will send at max, or did I get this wrong?

**Comment by Firedroide** [comment]
Yes, this is true. It's just that there has been an additional delay in reading the server response (not sending commands), which has been cut out and which should result in delay reductions.
