### ISSUE TITLE
Build path

### ISSUE THREAD

**Issue by Yunus1903** [TheHolyWaffle/TeamSpeak-3-Java-API#48]
When i add it to my Build Path in eclipse:
- i need a src version to see and use the code.

Please help me!

**Comment by Kakifrucht** [comment]
No you don't.

**Comment by Yunus1903** [comment]
Yes i do

**Comment by Yunus1903** [comment]
![GitHub Logo](http://puu.sh/iyxtZ/5ab6e67f23.png)

**Comment by Yunus1903** [comment]
Help Please!

**Comment by Kakifrucht** [comment]
Github is not a Java tutorial page. If you don't understand how to use an API, you should watch a tutorial first. If you have specific questions about the API, which are not already explained https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API#getting-started <-- there, feel free to ask them.

**Comment by Yunus1903** [comment]
Serious...
I just wanted some help.

**Comment by Yunus1903** [comment]
...

**Comment by Yunus1903** [comment]
Why can't you just help me...:|

**Comment by Yunus1903** [comment]
Please help meee

**Comment by Firedroide** [comment]
Tell me, are you 12 years old? Because you're really behaving like it. Let's break down what you're doing wrong:

- You've opened two issues in the last few hours screaming for help.
- You've closed and re-opened your first issue multiple times. Do you think we wouldn't see the first notice we get when someone opens an issue? Do you think spamming us will make it more likely we respond to you?
- Now on this second issue of yours, without even telling us what's wrong, you're spamming responses. Again, sending us countless e-mails in the process.

![image](https://cloud.githubusercontent.com/assets/1472572/8289028/1b9d4bc8-191a-11e5-93c4-974da239db00.png)

- And finally, your comments here don't even contain any content and show **no** efforts on your side in any way, shape, or form. This is an issue you could've easily solved by just googling it, without needing to cry for help here.

Do you not see how this behavior is unacceptable?

And, finally, for fucks sake, you're telling us that you need the source code of our API on **the very site where the source code is hosted!** There's even a button called "download ZIP"!
