### ISSUE TITLE
JoinEvent usually fires twice.

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#58]
Hello!
I just having an issue while some users are joining (the JoinEvent fires twice).

They are getting the message twice.

**Comment by Firedroide** [comment]
Was fixed in the snapshot builds. Update to [1.0.12-SNAPSHOT](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.12-SNAPSHOT/teamspeak3-api-1.0.12-20150812.204416-11.jar?raw=true) instead of using the latest release and you should be good.

Currently, you can only get snapshot builds from the mvn-repo branch of this repository.

**Comment by Scrumplex** [comment]
ok thanks
