### ISSUE TITLE
Beginning Help

### ISSUE THREAD

**Issue by lgund** [TheHolyWaffle/TeamSpeak-3-Java-API#60]
Hey,

i want write a function if somebody has a Servergroup that is definied the function say true.....

My Code:

    static int WEBINTERFACE_ADMIN_SGROUP            =   6;
    public boolean is_Admin(int clid)
    {
        boolean has_right                   =   false;
        
        for(int i = 0; i < clid.getServerGroups().length; i++)
        {
            if(clid.getServerGroups()[i] == WEBINTERFACE_ADMIN_SGROUP)
            {
                has_right                   =   true;
            }
        }
        
        return has_right;
    }

Any idea whats wrong ?? And sry i am new in Java :/

**Comment by Firedroide** [comment]
Hi!

I can see 3 problems with your code. 

The first issue is that you're trying to call `clid.getServerGroups()`; you're trying to call a method on "clid" which is an `int`. What you need to do instead is pass in the TS3Api object so you can execute API commands on it, like this

    public boolean is_Admin(TS3Api api, int clid) {
        [...]

The second one is that you're using the wrong API method to get a client's server groups. You can simply call `api.getClientInfo(clid)` to get back a `ClientInfo` object which contains an array of the IDs of the client's server groups. Then you just have to find out whether the server group you're looking for is actually in that array or not.

The third problem is that inside the loop, you're comparing `ServerGroup`s and `int`s using ==. == tests for equal values if you're comparing primitive types (like ints, longs, floats, etc.) and test for equal object references if you're comparing objects. You're currently trying to compare an object and a primitive type, which doesn't work.

You should, instead, compare the ID of the server group to the one you've stored in a final field:

    if (serverGroups[i].getId() == WEBINTERFACE_ADMIN_SGROUP) {
        [...]

And finally, there are a few stylistic options. First of all, you should maybe make `WEBINTERFACE_ADMIN_SGROUP` private and final, since you're not using it anywhere else. What is more, instead of using a "traditional" for loop, you could use a for-each loop to iterate over all elements in an array / a list.

To stitch it all together:

    private static final int WEBINTERFACE_ADMIN_SGROUP = 6;
    public boolean isServerAdmin(TS3Api api, int clid) {
        ClientInfo client = api.getClientInfo(clid);
        int[] serverGroupIDs = client.getServerGroups();
    
        for (int sgid : serverGroupIDs) {
            if (sgid == WEBINTERFACE_ADMIN_SGROUP) {
                return true;
            }
        }
        
        // No server groups with a matching ID
        return false;
    }

I hope I was able to help you :smiley:
If you have any other questions, feel free to ask them here.

**Comment by Kakifrucht** [comment]
Wow, you are pretty dedicated on helping him o.O
Honestly, I feel like if he has questions related to Java he shouldn't be asking them here, but I guess you like helping newbies.

**Comment by lgund** [comment]
THX for the fast answer ;) now all works fine ^^
