### ISSUE TITLE
No ClientLeaveEvent.getClientName() method?

### ISSUE THREAD

**Issue by Geforce132** [TheHolyWaffle/TeamSpeak-3-Java-API#65]
I'm using this API in my IRC bot, and want it to print out something like " * [name] has left [servername]" whenever someone leaves my TS3 server. I already have that working for the ClientJoinEvent, but I noticed there doesn't seems to be any "getClientName" method (or similar) in ClientLeaveEvent. I tried using .getInvokerName(), but that apparently returns an empty string. Any suggestions?

Thanks. :)

**Comment by TheHolyWaffle** [comment]
They way I handle this is by storing the username from ClientJoinEvent in a
hashmap somewhere and fetching it back in the ClientLeaveEvent.

2015-09-10 20:24 GMT+02:00 Geforce <notifications@github.com>:

**Comment by Kakifrucht** [comment]
Would this work? 
api.getClientInfo(e.getClientId()).getLoginName();

**Comment by TheHolyWaffle** [comment]
no, because the client has already left the server and so getClientInfo
won't find any info.

2015-09-10 20:46 GMT+02:00 Fabian <notifications@github.com>:

**Comment by Geforce132** [comment]
Ah, yes, that should solve my problem. Thanks. :+1:

**Comment by Firedroide** [comment]
Just as a side note: There is no "getClientName()" because no info about the client is transmitted in ClientLeaveEvent, except for the client's IDs. This API only acts as an interface between your code and the TS3 server, so we can't give you any information we don't have.

`getInvokerName()` gets you the nickname of the client who caused the event to happen. In your case this was an empty String because the client left by himself. If a client caused that event by kicking or banning someone, then could get the nickname and the IDs of that client (who kicked the other one).

Seeing how the question was resolved, I'll close this issue now.
