### ISSUE TITLE
LeaveEvent Unique ID?

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#68]
Hello!
I wanted to ask how I can get the uniqueid of a client who disconnects.

**Comment by Firedroide** [comment]
Hi Scrumplex!

This question has already been answered in #38, #65 and #43.
I hope it's okay if I refer you to my answers on these issues rather than typing it all out once again.

If anything is unclear or if I misunderstood your question, please re-open this issue :smile:
Otherwise I'll assume this issue has been resolved.
