### ISSUE TITLE
setClientDescription missing?

### ISSUE THREAD

**Issue by sourcemaker** [TheHolyWaffle/TeamSpeak-3-Java-API#70]
Hey there,

Thank you for this awsome api!
Is there a function to actually set the client description?
I was looking through your code, but just found the clientInfo.getDescription().

**Comment by Firedroide** [comment]
Call [api.updateClient(properties)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3587) with a [Collections.singletonMap](http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#singletonMap(K,%20V)) mapping ClientProperty.CLIENT_DESCRIPTION to your description.

You can use, provided you have the permissions to do so, [api.editClient(clientId, properties)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1177) to edit other clients' descriptions.

The clientedit command (which api.editClient abstracts) should actually be able to change many more properties for other clients, but currently it seems like it only accepts the property CLIENT_DESCRIPTION (because the server query interface is not feature-complete).

**Comment by sourcemaker** [comment]
Awww, that worked very well. Thank you very much Firedroid for the quick support!

**Comment by Firedroide** [comment]
You're very welcome! :smile:
