### ISSUE TITLE
Not an issue, more of a solution.

### ISSUE THREAD

**Issue by Punny123** [TheHolyWaffle/TeamSpeak-3-Java-API#72]
Hi I just figured out how to run the executed jar files in cmd when the program was built in netbeans.

open cmd in the project folder and run this command line:

mvn exec:java -Dexec.mainClass="MainClassName"

do not add .java at the end and keep the quotations.
Sorry if this was posted in the wrong place, I am new to github

**Comment by Firedroide** [comment]
You could've just commented on the closed issue ^^

Also, I wouldn't say that this is a correct or in any way appropriate solution. It would require the user to have the Maven build system installed, and why should they? All they have (and should have) installed is the Java runtime.

The *only* correct solution to this problem is adding a manifest file that specifies which class contains the "main" method.

This way the user can either double-click the jar file (which will not open a console window), or start the program from a command prompt by using **java** or **javaw**.

As this is not really relevant to this project, so I'll close this issue for now.
