### ISSUE TITLE
not as putting an icon to a channel

### ISSUE THREAD

**Issue by dm94** [TheHolyWaffle/TeamSpeak-3-Java-API#78]
Using "Channel Property.CHANNEL ICON_ID" as with other properties but does not work

**Comment by Firedroide** [comment]
You need to be a little more specific.

a) What was the code you used
b) What data was sent to and from the server? (See the console log / log file)
c) Was your TS3 server set up correctly? Did you use the correct icon ID? etc.

**Comment by Kakifrucht** [comment]
Actually I had the same issue.
Workaround would be TS3Api.addChannelPermission(channelID, "i_icon_id", (int) iconidhere);

**Comment by Firedroide** [comment]
I can't confirm your findings.

I just tested it and was able to edit the icon with this simple code snippet:

    api.editChannel(cid, Collections.singletonMap(ChannelProperty.CHANNEL_ICON_ID, "600"));

To ensure it wasn't because of the built-in icon, I uploaded my own icon and tested it with that. Same code, different ID - everything worked.

I need more input to figure out what could be wrong.

**Comment by Kakifrucht** [comment]
I can't test right now, but what did not work for me is add the property to the map, which is then passed to api.createChannel().

**Comment by Firedroide** [comment]
Okay, I can confirm that. I don't know if there's anything we could do about this, though. This seems to be primarily a TS3 bug.

**Comment by dm94** [comment]
Thanks for the solutions I will try with those forms
