### ISSUE TITLE
AsyncAPI getClients not work

### ISSUE THREAD

**Issue by MogliDerZauberKoenig** [TheHolyWaffle/TeamSpeak-3-Java-API#82]
Hi,

iam trying to get a list of clients in my runnable class.
`List<Client> clients = asyncApi.getClients();`
but it says: Type mismatch: cannot convert from CommandFuture<List<Client>> to List<Client>

**Comment by Firedroide** [comment]
Well, yeah, that's actually expected :smile:

The return type of the *synchronous* API for this method is `List<Client>`, however the return type of the *asynchronous* API is `CommandFuture<List<Client>>`.

That's simply because of how asynchroncity works: we can't give you the result to the method you called yet, because that response hasn't actually arrived. Instead, we give you an object with which you can access the data once it arrives or set up *success* and *failure* listeners. That's what `CommandFuture` does.

**Comment by MogliDerZauberKoenig** [comment]
Ohhhh okay thank you :+1:
