### ISSUE TITLE
[20:20:59 ERROR]: Error occurred while enabling TSAuth v1.0 (Is it up to date?) java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config

### ISSUE THREAD

**Issue by DoggyCode** [TheHolyWaffle/TeamSpeak-3-Java-API#86]
I'm getting a "**[20:20:59 ERROR]: Error occurred while enabling TSAuth v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config**" error.

This is my POM.xml:
http://hastebin.com/wimasacive.xml

I use IntelliJ and hit Build > Build Artifacts > build/rebuild

Anything wrong?

**Comment by Firedroide** [comment]
If you have Maven set up, why are you using the built-in build system instead of letting Maven generate your artifacts??

The problem is obvious, your (IntelliJ-internal) build configuration doesn't include this library in the artifact.

Use the Maven tool inside of IntelliJ and run the goals "clean package". That should fix your problem.

**Comment by DoggyCode** [comment]
There are no Maven in Tools > ...

**Comment by Firedroide** [comment]
-.-

Lower left corner -> Maven projects
Opens up a window. If you project is not in that window, select your POM file from the project explorer window and drag it over into the maven projects window.

And no, if your configuration did include all necessary classes, you wouldn't be getting the error that a class is missing.
