### ISSUE TITLE
[FEATURE] Command Preprocessor

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#87]
Hello there,
I think something like a command preprocessor would be nice. If any command has to be executed a preprocessor gets executed and if that one returns `true` the command will be sent to the ts3 server and so on.
Example method:
```java
//TS3Config ts3Config = ...
ts3Config.setCommandPreprocessor(new com.github.theholywaffle.teamspeak3.TS3CommandPreprocessor() {
    @Override
    public boolean processCommand(com.github.theholywaffle.teamspeak3.commands.Command cmd) {
        return AnyClassNameHere.isCommandAllowed(cmd); //returns a boolean
    }
});
//TS3Query ts3Query = ...
```
I think the implementation would be very easy.
Kind regards
Sefa E.
*//EDIT1: Syntax Highlighting + better example
//EDIT2: Fixed Brain AFK Bug*

**Comment by Firedroide** [comment]
What would be a good use case for such a preprocessor?
And what would it actually do? Just allow the command to go through if the returned value is `true` and block it otherwise?

**Comment by Scrumplex** [comment]
I could need it to block commands if my bot is shutting down, so that plugins are also forced to shutdown.
It should just block or allow commands.
It would also be neat to have own log files via this method

**Comment by Firedroide** [comment]
Hmm... Why not just disable the plugins before you do your own shutdown routine? Would also give your plugins the opportunity to execute some cleanup (or similar) commands before shutting down.

**Comment by Scrumplex** [comment]
I have an `onShutdown()` method for the plugins...
But not everyone cleans up everything.

**Comment by Firedroide** [comment]
I'm sorry I am so skeptical when it comes to new features, but I really don't want this project to bloat too much due to [feature creep](https://en.wikipedia.org/wiki/Feature_creep).

Such a preprocessor seems like just that kind of feature that would be used by less than one percent of people who use this API and the problem it tries to solve would've been solved better with some other tool anyways.

Speaking of which, would such a preprocessor not also stop your own program from sending any commands once it's being shut down? And what would stop plugins from maliciously using reflection to just remove the preprocessor again?

To quote a StackOverflow comment about inheritance: "There's only so much parents can do to stop their children doing something stupid."

**Comment by Scrumplex** [comment]
Okay you're right. I am just quite unsure how to properly unload an external jar.

**Comment by Firedroide** [comment]
I mean, if you pass the TS3Query or even the TS3Api object along to the plugin, them calling stuff you don't want during shutdown really is the least of your problem ^^

They might as well just call `quit` or `logout` or something like that at basically any time and your program would most likely stop working.

---

Unloading jars: I don't think there's an easy way to do this in Java. There's [OSGi](https://www.osgi.org/) which does modules with class loading and unloading, but I have no idea if it would be a good fit for your plugin environment :stuck_out_tongue:

**Comment by TheMolkaPL** [comment]
I see the famous `onDisable()` method... If it's Bukkit you [could disable](https://jd.bukkit.org/org/bukkit/plugin/PluginManager.html#disablePlugin(org.bukkit.plugin.Plugin)) the plugin via API.

**Comment by Firedroide** [comment]
@TheMolkaPL Yeah, but only kinda. It would stop your plugin from receiving events and stuff like that, but you could still create your own threads inside your plugin classes which would continue running even after the plugin being disabled. And if you'd then somehow reload your plugin, you could easily crash the whole server.

If I recall correctly, this was one of the reasons why they abandoned `/reload` and plugin reloading. Oh, and they're sending out warnings if you dare create your own threads instead of using their scheduler service :D

**Comment by Scrumplex** [comment]
Nah it is not Bukkit. I am writing my own bot (proudly powered by TeamSpeak-3-Java-API) and I added a plugin functionality to it months ago and I still dont have a proper plugin unloading function.

**Comment by Firedroide** [comment]
@Scrumplex

Yeah, but @TheMolkaPL mentioned it as it found itself in a very similar position as you are now :P

To really make your plugins safe, you'd have to at least
* Stop your plugins from creating their own Threads -> possibly with a SecurityManager
* Add your own scheduling service to enable threading-like behaviour you can easily shut down once that plugin gets disabled.
* Keep them from doing stuff with reflections -> also SecurityManager
* Do custom class loading so the plugins at least don't have direct access to this API's classes and unloading plugin classes becomes possible.
* Add your own layer between this API and your plugins which does stuff like permission checks, filtering out illegal commands, etc. -> You could probably do this by overriding TS3Api.
* Send events to plugins asynchronously and enforce time limits on the plugins.

... and this list probably goes on even longer ^^

In my opinion, going through all this effort is probably not worth it. Unless you want to just do it for fun / academic purposes :stuck_out_tongue:
