### ISSUE TITLE
Have a Error

### ISSUE THREAD

**Issue by Devil354** [TheHolyWaffle/TeamSpeak-3-Java-API#89]
How to get Client's Database by UID I used this code but it gave me a error 

register.java:82: error: cannot find symbol
                                asyncApi.addClientToServerGroup(795, getDatabaseId(getDatabaseClientByUId(uid)));
                                                                                   ^
  symbol: method getDatabaseClientByUId(String)

code - 
String uid = e.getInvokerUniqueId();
getDatabaseId(getDatabaseClientByUId(uid);

note : - I am new to java

**Comment by Firedroide** [comment]
If you're new to Java, you should maybe use the synchronous API instead of the asynchronous one. That would make your life a lot easier :D

    TS3Api api = .......;
    DatabaseClientInfo dbClient = api.getDatabaseClientByUId(uid);
    api.addClientToServerGroup(795, dbClient.getDatabaseId());

I'm writing this on mobile, so there might be mistakes in the code snippet above :D

Also note that the invoker is not the client who was affected by an event, but a client who caused that event to happen, e.g. by moving / kicking / banning another client. If there was no invoker (e.g. a client moved by themselves), that getInvokerUniqueId will return an empty string.

**Comment by Devil354** [comment]
Thank you mate for such quick and accurate solution I can't believe i spend 2 days trying to figure it out by myself :D once again thank you very much

**Comment by Firedroide** [comment]
You welcome! By the way, for quick questions like this we also have a Gitter channel. You might get answers there even quicker there ^^

**Comment by Devil354** [comment]
how can i join it ?

**Comment by Firedroide** [comment]
Forgot to link you to it:
https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API

You can also find this link in the readme / project description.
